// @ts-types="npm:@types/node"
/// <reference types="deno.ns" />
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: Deno.env.get("DATABASE_URL") || "file:./gastro.db",
  },
});
