
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Song.ts'
export type * from './models/Artist.ts'
export type * from './models/Album.ts'
export type * from './models/Genre.ts'
export type * from './commonInputTypes.ts'