
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Bestellung` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Bestellung
 * 
 */
export type BestellungModel = runtime.Types.Result.DefaultSelection<Prisma.$BestellungPayload>

export type AggregateBestellung = {
  _count: BestellungCountAggregateOutputType | null
  _avg: BestellungAvgAggregateOutputType | null
  _sum: BestellungSumAggregateOutputType | null
  _min: BestellungMinAggregateOutputType | null
  _max: BestellungMaxAggregateOutputType | null
}

export type BestellungAvgAggregateOutputType = {
  id: number | null
  tischId: number | null
}

export type BestellungSumAggregateOutputType = {
  id: number | null
  tischId: number | null
}

export type BestellungMinAggregateOutputType = {
  id: number | null
  tischId: number | null
}

export type BestellungMaxAggregateOutputType = {
  id: number | null
  tischId: number | null
}

export type BestellungCountAggregateOutputType = {
  id: number
  tischId: number
  _all: number
}


export type BestellungAvgAggregateInputType = {
  id?: true
  tischId?: true
}

export type BestellungSumAggregateInputType = {
  id?: true
  tischId?: true
}

export type BestellungMinAggregateInputType = {
  id?: true
  tischId?: true
}

export type BestellungMaxAggregateInputType = {
  id?: true
  tischId?: true
}

export type BestellungCountAggregateInputType = {
  id?: true
  tischId?: true
  _all?: true
}

export type BestellungAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Bestellung to aggregate.
   */
  where?: Prisma.BestellungWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Bestellungs to fetch.
   */
  orderBy?: Prisma.BestellungOrderByWithRelationInput | Prisma.BestellungOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BestellungWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Bestellungs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Bestellungs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Bestellungs
  **/
  _count?: true | BestellungCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: BestellungAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: BestellungSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BestellungMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BestellungMaxAggregateInputType
}

export type GetBestellungAggregateType<T extends BestellungAggregateArgs> = {
      [P in keyof T & keyof AggregateBestellung]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBestellung[P]>
    : Prisma.GetScalarType<T[P], AggregateBestellung[P]>
}




export type BestellungGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BestellungWhereInput
  orderBy?: Prisma.BestellungOrderByWithAggregationInput | Prisma.BestellungOrderByWithAggregationInput[]
  by: Prisma.BestellungScalarFieldEnum[] | Prisma.BestellungScalarFieldEnum
  having?: Prisma.BestellungScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BestellungCountAggregateInputType | true
  _avg?: BestellungAvgAggregateInputType
  _sum?: BestellungSumAggregateInputType
  _min?: BestellungMinAggregateInputType
  _max?: BestellungMaxAggregateInputType
}

export type BestellungGroupByOutputType = {
  id: number
  tischId: number
  _count: BestellungCountAggregateOutputType | null
  _avg: BestellungAvgAggregateOutputType | null
  _sum: BestellungSumAggregateOutputType | null
  _min: BestellungMinAggregateOutputType | null
  _max: BestellungMaxAggregateOutputType | null
}

type GetBestellungGroupByPayload<T extends BestellungGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BestellungGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BestellungGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BestellungGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BestellungGroupByOutputType[P]>
      }
    >
  >



export type BestellungWhereInput = {
  AND?: Prisma.BestellungWhereInput | Prisma.BestellungWhereInput[]
  OR?: Prisma.BestellungWhereInput[]
  NOT?: Prisma.BestellungWhereInput | Prisma.BestellungWhereInput[]
  id?: Prisma.IntFilter<"Bestellung"> | number
  tischId?: Prisma.IntFilter<"Bestellung"> | number
  tisch?: Prisma.XOR<Prisma.TischScalarRelationFilter, Prisma.TischWhereInput>
  bestellzeilen?: Prisma.BestellzeileListRelationFilter
}

export type BestellungOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  tischId?: Prisma.SortOrder
  tisch?: Prisma.TischOrderByWithRelationInput
  bestellzeilen?: Prisma.BestellzeileOrderByRelationAggregateInput
}

export type BestellungWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  tischId?: number
  AND?: Prisma.BestellungWhereInput | Prisma.BestellungWhereInput[]
  OR?: Prisma.BestellungWhereInput[]
  NOT?: Prisma.BestellungWhereInput | Prisma.BestellungWhereInput[]
  tisch?: Prisma.XOR<Prisma.TischScalarRelationFilter, Prisma.TischWhereInput>
  bestellzeilen?: Prisma.BestellzeileListRelationFilter
}, "id" | "tischId">

export type BestellungOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  tischId?: Prisma.SortOrder
  _count?: Prisma.BestellungCountOrderByAggregateInput
  _avg?: Prisma.BestellungAvgOrderByAggregateInput
  _max?: Prisma.BestellungMaxOrderByAggregateInput
  _min?: Prisma.BestellungMinOrderByAggregateInput
  _sum?: Prisma.BestellungSumOrderByAggregateInput
}

export type BestellungScalarWhereWithAggregatesInput = {
  AND?: Prisma.BestellungScalarWhereWithAggregatesInput | Prisma.BestellungScalarWhereWithAggregatesInput[]
  OR?: Prisma.BestellungScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BestellungScalarWhereWithAggregatesInput | Prisma.BestellungScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Bestellung"> | number
  tischId?: Prisma.IntWithAggregatesFilter<"Bestellung"> | number
}

export type BestellungCreateInput = {
  tisch: Prisma.TischCreateNestedOneWithoutBestellungInput
  bestellzeilen?: Prisma.BestellzeileCreateNestedManyWithoutBestellungInput
}

export type BestellungUncheckedCreateInput = {
  id?: number
  tischId: number
  bestellzeilen?: Prisma.BestellzeileUncheckedCreateNestedManyWithoutBestellungInput
}

export type BestellungUpdateInput = {
  tisch?: Prisma.TischUpdateOneRequiredWithoutBestellungNestedInput
  bestellzeilen?: Prisma.BestellzeileUpdateManyWithoutBestellungNestedInput
}

export type BestellungUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tischId?: Prisma.IntFieldUpdateOperationsInput | number
  bestellzeilen?: Prisma.BestellzeileUncheckedUpdateManyWithoutBestellungNestedInput
}

export type BestellungCreateManyInput = {
  id?: number
  tischId: number
}

export type BestellungUpdateManyMutationInput = {

}

export type BestellungUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tischId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type BestellungNullableScalarRelationFilter = {
  is?: Prisma.BestellungWhereInput | null
  isNot?: Prisma.BestellungWhereInput | null
}

export type BestellungCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tischId?: Prisma.SortOrder
}

export type BestellungAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tischId?: Prisma.SortOrder
}

export type BestellungMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tischId?: Prisma.SortOrder
}

export type BestellungMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tischId?: Prisma.SortOrder
}

export type BestellungSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tischId?: Prisma.SortOrder
}

export type BestellungScalarRelationFilter = {
  is?: Prisma.BestellungWhereInput
  isNot?: Prisma.BestellungWhereInput
}

export type BestellungCreateNestedOneWithoutTischInput = {
  create?: Prisma.XOR<Prisma.BestellungCreateWithoutTischInput, Prisma.BestellungUncheckedCreateWithoutTischInput>
  connectOrCreate?: Prisma.BestellungCreateOrConnectWithoutTischInput
  connect?: Prisma.BestellungWhereUniqueInput
}

export type BestellungUncheckedCreateNestedOneWithoutTischInput = {
  create?: Prisma.XOR<Prisma.BestellungCreateWithoutTischInput, Prisma.BestellungUncheckedCreateWithoutTischInput>
  connectOrCreate?: Prisma.BestellungCreateOrConnectWithoutTischInput
  connect?: Prisma.BestellungWhereUniqueInput
}

export type BestellungUpdateOneWithoutTischNestedInput = {
  create?: Prisma.XOR<Prisma.BestellungCreateWithoutTischInput, Prisma.BestellungUncheckedCreateWithoutTischInput>
  connectOrCreate?: Prisma.BestellungCreateOrConnectWithoutTischInput
  upsert?: Prisma.BestellungUpsertWithoutTischInput
  disconnect?: Prisma.BestellungWhereInput | boolean
  delete?: Prisma.BestellungWhereInput | boolean
  connect?: Prisma.BestellungWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BestellungUpdateToOneWithWhereWithoutTischInput, Prisma.BestellungUpdateWithoutTischInput>, Prisma.BestellungUncheckedUpdateWithoutTischInput>
}

export type BestellungUncheckedUpdateOneWithoutTischNestedInput = {
  create?: Prisma.XOR<Prisma.BestellungCreateWithoutTischInput, Prisma.BestellungUncheckedCreateWithoutTischInput>
  connectOrCreate?: Prisma.BestellungCreateOrConnectWithoutTischInput
  upsert?: Prisma.BestellungUpsertWithoutTischInput
  disconnect?: Prisma.BestellungWhereInput | boolean
  delete?: Prisma.BestellungWhereInput | boolean
  connect?: Prisma.BestellungWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BestellungUpdateToOneWithWhereWithoutTischInput, Prisma.BestellungUpdateWithoutTischInput>, Prisma.BestellungUncheckedUpdateWithoutTischInput>
}

export type BestellungCreateNestedOneWithoutBestellzeilenInput = {
  create?: Prisma.XOR<Prisma.BestellungCreateWithoutBestellzeilenInput, Prisma.BestellungUncheckedCreateWithoutBestellzeilenInput>
  connectOrCreate?: Prisma.BestellungCreateOrConnectWithoutBestellzeilenInput
  connect?: Prisma.BestellungWhereUniqueInput
}

export type BestellungUpdateOneRequiredWithoutBestellzeilenNestedInput = {
  create?: Prisma.XOR<Prisma.BestellungCreateWithoutBestellzeilenInput, Prisma.BestellungUncheckedCreateWithoutBestellzeilenInput>
  connectOrCreate?: Prisma.BestellungCreateOrConnectWithoutBestellzeilenInput
  upsert?: Prisma.BestellungUpsertWithoutBestellzeilenInput
  connect?: Prisma.BestellungWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BestellungUpdateToOneWithWhereWithoutBestellzeilenInput, Prisma.BestellungUpdateWithoutBestellzeilenInput>, Prisma.BestellungUncheckedUpdateWithoutBestellzeilenInput>
}

export type BestellungCreateWithoutTischInput = {
  bestellzeilen?: Prisma.BestellzeileCreateNestedManyWithoutBestellungInput
}

export type BestellungUncheckedCreateWithoutTischInput = {
  id?: number
  bestellzeilen?: Prisma.BestellzeileUncheckedCreateNestedManyWithoutBestellungInput
}

export type BestellungCreateOrConnectWithoutTischInput = {
  where: Prisma.BestellungWhereUniqueInput
  create: Prisma.XOR<Prisma.BestellungCreateWithoutTischInput, Prisma.BestellungUncheckedCreateWithoutTischInput>
}

export type BestellungUpsertWithoutTischInput = {
  update: Prisma.XOR<Prisma.BestellungUpdateWithoutTischInput, Prisma.BestellungUncheckedUpdateWithoutTischInput>
  create: Prisma.XOR<Prisma.BestellungCreateWithoutTischInput, Prisma.BestellungUncheckedCreateWithoutTischInput>
  where?: Prisma.BestellungWhereInput
}

export type BestellungUpdateToOneWithWhereWithoutTischInput = {
  where?: Prisma.BestellungWhereInput
  data: Prisma.XOR<Prisma.BestellungUpdateWithoutTischInput, Prisma.BestellungUncheckedUpdateWithoutTischInput>
}

export type BestellungUpdateWithoutTischInput = {
  bestellzeilen?: Prisma.BestellzeileUpdateManyWithoutBestellungNestedInput
}

export type BestellungUncheckedUpdateWithoutTischInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  bestellzeilen?: Prisma.BestellzeileUncheckedUpdateManyWithoutBestellungNestedInput
}

export type BestellungCreateWithoutBestellzeilenInput = {
  tisch: Prisma.TischCreateNestedOneWithoutBestellungInput
}

export type BestellungUncheckedCreateWithoutBestellzeilenInput = {
  id?: number
  tischId: number
}

export type BestellungCreateOrConnectWithoutBestellzeilenInput = {
  where: Prisma.BestellungWhereUniqueInput
  create: Prisma.XOR<Prisma.BestellungCreateWithoutBestellzeilenInput, Prisma.BestellungUncheckedCreateWithoutBestellzeilenInput>
}

export type BestellungUpsertWithoutBestellzeilenInput = {
  update: Prisma.XOR<Prisma.BestellungUpdateWithoutBestellzeilenInput, Prisma.BestellungUncheckedUpdateWithoutBestellzeilenInput>
  create: Prisma.XOR<Prisma.BestellungCreateWithoutBestellzeilenInput, Prisma.BestellungUncheckedCreateWithoutBestellzeilenInput>
  where?: Prisma.BestellungWhereInput
}

export type BestellungUpdateToOneWithWhereWithoutBestellzeilenInput = {
  where?: Prisma.BestellungWhereInput
  data: Prisma.XOR<Prisma.BestellungUpdateWithoutBestellzeilenInput, Prisma.BestellungUncheckedUpdateWithoutBestellzeilenInput>
}

export type BestellungUpdateWithoutBestellzeilenInput = {
  tisch?: Prisma.TischUpdateOneRequiredWithoutBestellungNestedInput
}

export type BestellungUncheckedUpdateWithoutBestellzeilenInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tischId?: Prisma.IntFieldUpdateOperationsInput | number
}


/**
 * Count Type BestellungCountOutputType
 */

export type BestellungCountOutputType = {
  bestellzeilen: number
}

export type BestellungCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bestellzeilen?: boolean | BestellungCountOutputTypeCountBestellzeilenArgs
}

/**
 * BestellungCountOutputType without action
 */
export type BestellungCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestellungCountOutputType
   */
  select?: Prisma.BestellungCountOutputTypeSelect<ExtArgs> | null
}

/**
 * BestellungCountOutputType without action
 */
export type BestellungCountOutputTypeCountBestellzeilenArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BestellzeileWhereInput
}


export type BestellungSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tischId?: boolean
  tisch?: boolean | Prisma.TischDefaultArgs<ExtArgs>
  bestellzeilen?: boolean | Prisma.Bestellung$bestellzeilenArgs<ExtArgs>
  _count?: boolean | Prisma.BestellungCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bestellung"]>

export type BestellungSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tischId?: boolean
  tisch?: boolean | Prisma.TischDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bestellung"]>

export type BestellungSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tischId?: boolean
  tisch?: boolean | Prisma.TischDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bestellung"]>

export type BestellungSelectScalar = {
  id?: boolean
  tischId?: boolean
}

export type BestellungOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "tischId", ExtArgs["result"]["bestellung"]>
export type BestellungInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tisch?: boolean | Prisma.TischDefaultArgs<ExtArgs>
  bestellzeilen?: boolean | Prisma.Bestellung$bestellzeilenArgs<ExtArgs>
  _count?: boolean | Prisma.BestellungCountOutputTypeDefaultArgs<ExtArgs>
}
export type BestellungIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tisch?: boolean | Prisma.TischDefaultArgs<ExtArgs>
}
export type BestellungIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tisch?: boolean | Prisma.TischDefaultArgs<ExtArgs>
}

export type $BestellungPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Bestellung"
  objects: {
    tisch: Prisma.$TischPayload<ExtArgs>
    bestellzeilen: Prisma.$BestellzeilePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    tischId: number
  }, ExtArgs["result"]["bestellung"]>
  composites: {}
}

export type BestellungGetPayload<S extends boolean | null | undefined | BestellungDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BestellungPayload, S>

export type BestellungCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BestellungFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BestellungCountAggregateInputType | true
  }

export interface BestellungDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Bestellung'], meta: { name: 'Bestellung' } }
  /**
   * Find zero or one Bestellung that matches the filter.
   * @param {BestellungFindUniqueArgs} args - Arguments to find a Bestellung
   * @example
   * // Get one Bestellung
   * const bestellung = await prisma.bestellung.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BestellungFindUniqueArgs>(args: Prisma.SelectSubset<T, BestellungFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BestellungClient<runtime.Types.Result.GetResult<Prisma.$BestellungPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Bestellung that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BestellungFindUniqueOrThrowArgs} args - Arguments to find a Bestellung
   * @example
   * // Get one Bestellung
   * const bestellung = await prisma.bestellung.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BestellungFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BestellungFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BestellungClient<runtime.Types.Result.GetResult<Prisma.$BestellungPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Bestellung that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestellungFindFirstArgs} args - Arguments to find a Bestellung
   * @example
   * // Get one Bestellung
   * const bestellung = await prisma.bestellung.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BestellungFindFirstArgs>(args?: Prisma.SelectSubset<T, BestellungFindFirstArgs<ExtArgs>>): Prisma.Prisma__BestellungClient<runtime.Types.Result.GetResult<Prisma.$BestellungPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Bestellung that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestellungFindFirstOrThrowArgs} args - Arguments to find a Bestellung
   * @example
   * // Get one Bestellung
   * const bestellung = await prisma.bestellung.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BestellungFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BestellungFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BestellungClient<runtime.Types.Result.GetResult<Prisma.$BestellungPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Bestellungs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestellungFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Bestellungs
   * const bestellungs = await prisma.bestellung.findMany()
   * 
   * // Get first 10 Bestellungs
   * const bestellungs = await prisma.bestellung.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const bestellungWithIdOnly = await prisma.bestellung.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BestellungFindManyArgs>(args?: Prisma.SelectSubset<T, BestellungFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BestellungPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Bestellung.
   * @param {BestellungCreateArgs} args - Arguments to create a Bestellung.
   * @example
   * // Create one Bestellung
   * const Bestellung = await prisma.bestellung.create({
   *   data: {
   *     // ... data to create a Bestellung
   *   }
   * })
   * 
   */
  create<T extends BestellungCreateArgs>(args: Prisma.SelectSubset<T, BestellungCreateArgs<ExtArgs>>): Prisma.Prisma__BestellungClient<runtime.Types.Result.GetResult<Prisma.$BestellungPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Bestellungs.
   * @param {BestellungCreateManyArgs} args - Arguments to create many Bestellungs.
   * @example
   * // Create many Bestellungs
   * const bestellung = await prisma.bestellung.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BestellungCreateManyArgs>(args?: Prisma.SelectSubset<T, BestellungCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Bestellungs and returns the data saved in the database.
   * @param {BestellungCreateManyAndReturnArgs} args - Arguments to create many Bestellungs.
   * @example
   * // Create many Bestellungs
   * const bestellung = await prisma.bestellung.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Bestellungs and only return the `id`
   * const bestellungWithIdOnly = await prisma.bestellung.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BestellungCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BestellungCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BestellungPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Bestellung.
   * @param {BestellungDeleteArgs} args - Arguments to delete one Bestellung.
   * @example
   * // Delete one Bestellung
   * const Bestellung = await prisma.bestellung.delete({
   *   where: {
   *     // ... filter to delete one Bestellung
   *   }
   * })
   * 
   */
  delete<T extends BestellungDeleteArgs>(args: Prisma.SelectSubset<T, BestellungDeleteArgs<ExtArgs>>): Prisma.Prisma__BestellungClient<runtime.Types.Result.GetResult<Prisma.$BestellungPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Bestellung.
   * @param {BestellungUpdateArgs} args - Arguments to update one Bestellung.
   * @example
   * // Update one Bestellung
   * const bestellung = await prisma.bestellung.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BestellungUpdateArgs>(args: Prisma.SelectSubset<T, BestellungUpdateArgs<ExtArgs>>): Prisma.Prisma__BestellungClient<runtime.Types.Result.GetResult<Prisma.$BestellungPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Bestellungs.
   * @param {BestellungDeleteManyArgs} args - Arguments to filter Bestellungs to delete.
   * @example
   * // Delete a few Bestellungs
   * const { count } = await prisma.bestellung.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BestellungDeleteManyArgs>(args?: Prisma.SelectSubset<T, BestellungDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Bestellungs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestellungUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Bestellungs
   * const bestellung = await prisma.bestellung.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BestellungUpdateManyArgs>(args: Prisma.SelectSubset<T, BestellungUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Bestellungs and returns the data updated in the database.
   * @param {BestellungUpdateManyAndReturnArgs} args - Arguments to update many Bestellungs.
   * @example
   * // Update many Bestellungs
   * const bestellung = await prisma.bestellung.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Bestellungs and only return the `id`
   * const bestellungWithIdOnly = await prisma.bestellung.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BestellungUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BestellungUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BestellungPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Bestellung.
   * @param {BestellungUpsertArgs} args - Arguments to update or create a Bestellung.
   * @example
   * // Update or create a Bestellung
   * const bestellung = await prisma.bestellung.upsert({
   *   create: {
   *     // ... data to create a Bestellung
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Bestellung we want to update
   *   }
   * })
   */
  upsert<T extends BestellungUpsertArgs>(args: Prisma.SelectSubset<T, BestellungUpsertArgs<ExtArgs>>): Prisma.Prisma__BestellungClient<runtime.Types.Result.GetResult<Prisma.$BestellungPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Bestellungs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestellungCountArgs} args - Arguments to filter Bestellungs to count.
   * @example
   * // Count the number of Bestellungs
   * const count = await prisma.bestellung.count({
   *   where: {
   *     // ... the filter for the Bestellungs we want to count
   *   }
   * })
  **/
  count<T extends BestellungCountArgs>(
    args?: Prisma.Subset<T, BestellungCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BestellungCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Bestellung.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestellungAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BestellungAggregateArgs>(args: Prisma.Subset<T, BestellungAggregateArgs>): Prisma.PrismaPromise<GetBestellungAggregateType<T>>

  /**
   * Group by Bestellung.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestellungGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BestellungGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BestellungGroupByArgs['orderBy'] }
      : { orderBy?: BestellungGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BestellungGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBestellungGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Bestellung model
 */
readonly fields: BestellungFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Bestellung.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BestellungClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tisch<T extends Prisma.TischDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TischDefaultArgs<ExtArgs>>): Prisma.Prisma__TischClient<runtime.Types.Result.GetResult<Prisma.$TischPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  bestellzeilen<T extends Prisma.Bestellung$bestellzeilenArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Bestellung$bestellzeilenArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BestellzeilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Bestellung model
 */
export interface BestellungFieldRefs {
  readonly id: Prisma.FieldRef<"Bestellung", 'Int'>
  readonly tischId: Prisma.FieldRef<"Bestellung", 'Int'>
}
    

// Custom InputTypes
/**
 * Bestellung findUnique
 */
export type BestellungFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestellung
   */
  select?: Prisma.BestellungSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestellung
   */
  omit?: Prisma.BestellungOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestellungInclude<ExtArgs> | null
  /**
   * Filter, which Bestellung to fetch.
   */
  where: Prisma.BestellungWhereUniqueInput
}

/**
 * Bestellung findUniqueOrThrow
 */
export type BestellungFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestellung
   */
  select?: Prisma.BestellungSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestellung
   */
  omit?: Prisma.BestellungOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestellungInclude<ExtArgs> | null
  /**
   * Filter, which Bestellung to fetch.
   */
  where: Prisma.BestellungWhereUniqueInput
}

/**
 * Bestellung findFirst
 */
export type BestellungFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestellung
   */
  select?: Prisma.BestellungSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestellung
   */
  omit?: Prisma.BestellungOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestellungInclude<ExtArgs> | null
  /**
   * Filter, which Bestellung to fetch.
   */
  where?: Prisma.BestellungWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Bestellungs to fetch.
   */
  orderBy?: Prisma.BestellungOrderByWithRelationInput | Prisma.BestellungOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Bestellungs.
   */
  cursor?: Prisma.BestellungWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Bestellungs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Bestellungs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Bestellungs.
   */
  distinct?: Prisma.BestellungScalarFieldEnum | Prisma.BestellungScalarFieldEnum[]
}

/**
 * Bestellung findFirstOrThrow
 */
export type BestellungFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestellung
   */
  select?: Prisma.BestellungSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestellung
   */
  omit?: Prisma.BestellungOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestellungInclude<ExtArgs> | null
  /**
   * Filter, which Bestellung to fetch.
   */
  where?: Prisma.BestellungWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Bestellungs to fetch.
   */
  orderBy?: Prisma.BestellungOrderByWithRelationInput | Prisma.BestellungOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Bestellungs.
   */
  cursor?: Prisma.BestellungWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Bestellungs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Bestellungs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Bestellungs.
   */
  distinct?: Prisma.BestellungScalarFieldEnum | Prisma.BestellungScalarFieldEnum[]
}

/**
 * Bestellung findMany
 */
export type BestellungFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestellung
   */
  select?: Prisma.BestellungSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestellung
   */
  omit?: Prisma.BestellungOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestellungInclude<ExtArgs> | null
  /**
   * Filter, which Bestellungs to fetch.
   */
  where?: Prisma.BestellungWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Bestellungs to fetch.
   */
  orderBy?: Prisma.BestellungOrderByWithRelationInput | Prisma.BestellungOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Bestellungs.
   */
  cursor?: Prisma.BestellungWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Bestellungs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Bestellungs.
   */
  skip?: number
  distinct?: Prisma.BestellungScalarFieldEnum | Prisma.BestellungScalarFieldEnum[]
}

/**
 * Bestellung create
 */
export type BestellungCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestellung
   */
  select?: Prisma.BestellungSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestellung
   */
  omit?: Prisma.BestellungOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestellungInclude<ExtArgs> | null
  /**
   * The data needed to create a Bestellung.
   */
  data: Prisma.XOR<Prisma.BestellungCreateInput, Prisma.BestellungUncheckedCreateInput>
}

/**
 * Bestellung createMany
 */
export type BestellungCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Bestellungs.
   */
  data: Prisma.BestellungCreateManyInput | Prisma.BestellungCreateManyInput[]
}

/**
 * Bestellung createManyAndReturn
 */
export type BestellungCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestellung
   */
  select?: Prisma.BestellungSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Bestellung
   */
  omit?: Prisma.BestellungOmit<ExtArgs> | null
  /**
   * The data used to create many Bestellungs.
   */
  data: Prisma.BestellungCreateManyInput | Prisma.BestellungCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestellungIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Bestellung update
 */
export type BestellungUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestellung
   */
  select?: Prisma.BestellungSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestellung
   */
  omit?: Prisma.BestellungOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestellungInclude<ExtArgs> | null
  /**
   * The data needed to update a Bestellung.
   */
  data: Prisma.XOR<Prisma.BestellungUpdateInput, Prisma.BestellungUncheckedUpdateInput>
  /**
   * Choose, which Bestellung to update.
   */
  where: Prisma.BestellungWhereUniqueInput
}

/**
 * Bestellung updateMany
 */
export type BestellungUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Bestellungs.
   */
  data: Prisma.XOR<Prisma.BestellungUpdateManyMutationInput, Prisma.BestellungUncheckedUpdateManyInput>
  /**
   * Filter which Bestellungs to update
   */
  where?: Prisma.BestellungWhereInput
  /**
   * Limit how many Bestellungs to update.
   */
  limit?: number
}

/**
 * Bestellung updateManyAndReturn
 */
export type BestellungUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestellung
   */
  select?: Prisma.BestellungSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Bestellung
   */
  omit?: Prisma.BestellungOmit<ExtArgs> | null
  /**
   * The data used to update Bestellungs.
   */
  data: Prisma.XOR<Prisma.BestellungUpdateManyMutationInput, Prisma.BestellungUncheckedUpdateManyInput>
  /**
   * Filter which Bestellungs to update
   */
  where?: Prisma.BestellungWhereInput
  /**
   * Limit how many Bestellungs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestellungIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Bestellung upsert
 */
export type BestellungUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestellung
   */
  select?: Prisma.BestellungSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestellung
   */
  omit?: Prisma.BestellungOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestellungInclude<ExtArgs> | null
  /**
   * The filter to search for the Bestellung to update in case it exists.
   */
  where: Prisma.BestellungWhereUniqueInput
  /**
   * In case the Bestellung found by the `where` argument doesn't exist, create a new Bestellung with this data.
   */
  create: Prisma.XOR<Prisma.BestellungCreateInput, Prisma.BestellungUncheckedCreateInput>
  /**
   * In case the Bestellung was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BestellungUpdateInput, Prisma.BestellungUncheckedUpdateInput>
}

/**
 * Bestellung delete
 */
export type BestellungDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestellung
   */
  select?: Prisma.BestellungSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestellung
   */
  omit?: Prisma.BestellungOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestellungInclude<ExtArgs> | null
  /**
   * Filter which Bestellung to delete.
   */
  where: Prisma.BestellungWhereUniqueInput
}

/**
 * Bestellung deleteMany
 */
export type BestellungDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Bestellungs to delete
   */
  where?: Prisma.BestellungWhereInput
  /**
   * Limit how many Bestellungs to delete.
   */
  limit?: number
}

/**
 * Bestellung.bestellzeilen
 */
export type Bestellung$bestellzeilenArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestellzeile
   */
  select?: Prisma.BestellzeileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestellzeile
   */
  omit?: Prisma.BestellzeileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestellzeileInclude<ExtArgs> | null
  where?: Prisma.BestellzeileWhereInput
  orderBy?: Prisma.BestellzeileOrderByWithRelationInput | Prisma.BestellzeileOrderByWithRelationInput[]
  cursor?: Prisma.BestellzeileWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BestellzeileScalarFieldEnum | Prisma.BestellzeileScalarFieldEnum[]
}

/**
 * Bestellung without action
 */
export type BestellungDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestellung
   */
  select?: Prisma.BestellungSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestellung
   */
  omit?: Prisma.BestellungOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestellungInclude<ExtArgs> | null
}
