
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Speise` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Speise
 * 
 */
export type SpeiseModel = runtime.Types.Result.DefaultSelection<Prisma.$SpeisePayload>

export type AggregateSpeise = {
  _count: SpeiseCountAggregateOutputType | null
  _avg: SpeiseAvgAggregateOutputType | null
  _sum: SpeiseSumAggregateOutputType | null
  _min: SpeiseMinAggregateOutputType | null
  _max: SpeiseMaxAggregateOutputType | null
}

export type SpeiseAvgAggregateOutputType = {
  id: number | null
}

export type SpeiseSumAggregateOutputType = {
  id: number | null
}

export type SpeiseMinAggregateOutputType = {
  id: number | null
  speise: string | null
}

export type SpeiseMaxAggregateOutputType = {
  id: number | null
  speise: string | null
}

export type SpeiseCountAggregateOutputType = {
  id: number
  speise: number
  _all: number
}


export type SpeiseAvgAggregateInputType = {
  id?: true
}

export type SpeiseSumAggregateInputType = {
  id?: true
}

export type SpeiseMinAggregateInputType = {
  id?: true
  speise?: true
}

export type SpeiseMaxAggregateInputType = {
  id?: true
  speise?: true
}

export type SpeiseCountAggregateInputType = {
  id?: true
  speise?: true
  _all?: true
}

export type SpeiseAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Speise to aggregate.
   */
  where?: Prisma.SpeiseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Speises to fetch.
   */
  orderBy?: Prisma.SpeiseOrderByWithRelationInput | Prisma.SpeiseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SpeiseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Speises from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Speises.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Speises
  **/
  _count?: true | SpeiseCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SpeiseAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SpeiseSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SpeiseMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SpeiseMaxAggregateInputType
}

export type GetSpeiseAggregateType<T extends SpeiseAggregateArgs> = {
      [P in keyof T & keyof AggregateSpeise]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSpeise[P]>
    : Prisma.GetScalarType<T[P], AggregateSpeise[P]>
}




export type SpeiseGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SpeiseWhereInput
  orderBy?: Prisma.SpeiseOrderByWithAggregationInput | Prisma.SpeiseOrderByWithAggregationInput[]
  by: Prisma.SpeiseScalarFieldEnum[] | Prisma.SpeiseScalarFieldEnum
  having?: Prisma.SpeiseScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SpeiseCountAggregateInputType | true
  _avg?: SpeiseAvgAggregateInputType
  _sum?: SpeiseSumAggregateInputType
  _min?: SpeiseMinAggregateInputType
  _max?: SpeiseMaxAggregateInputType
}

export type SpeiseGroupByOutputType = {
  id: number
  speise: string
  _count: SpeiseCountAggregateOutputType | null
  _avg: SpeiseAvgAggregateOutputType | null
  _sum: SpeiseSumAggregateOutputType | null
  _min: SpeiseMinAggregateOutputType | null
  _max: SpeiseMaxAggregateOutputType | null
}

type GetSpeiseGroupByPayload<T extends SpeiseGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SpeiseGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SpeiseGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SpeiseGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SpeiseGroupByOutputType[P]>
      }
    >
  >



export type SpeiseWhereInput = {
  AND?: Prisma.SpeiseWhereInput | Prisma.SpeiseWhereInput[]
  OR?: Prisma.SpeiseWhereInput[]
  NOT?: Prisma.SpeiseWhereInput | Prisma.SpeiseWhereInput[]
  id?: Prisma.IntFilter<"Speise"> | number
  speise?: Prisma.StringFilter<"Speise"> | string
  allergene?: Prisma.AllergenListRelationFilter
  bestellzeilen?: Prisma.BestellzeileListRelationFilter
}

export type SpeiseOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  speise?: Prisma.SortOrder
  allergene?: Prisma.AllergenOrderByRelationAggregateInput
  bestellzeilen?: Prisma.BestellzeileOrderByRelationAggregateInput
}

export type SpeiseWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.SpeiseWhereInput | Prisma.SpeiseWhereInput[]
  OR?: Prisma.SpeiseWhereInput[]
  NOT?: Prisma.SpeiseWhereInput | Prisma.SpeiseWhereInput[]
  speise?: Prisma.StringFilter<"Speise"> | string
  allergene?: Prisma.AllergenListRelationFilter
  bestellzeilen?: Prisma.BestellzeileListRelationFilter
}, "id">

export type SpeiseOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  speise?: Prisma.SortOrder
  _count?: Prisma.SpeiseCountOrderByAggregateInput
  _avg?: Prisma.SpeiseAvgOrderByAggregateInput
  _max?: Prisma.SpeiseMaxOrderByAggregateInput
  _min?: Prisma.SpeiseMinOrderByAggregateInput
  _sum?: Prisma.SpeiseSumOrderByAggregateInput
}

export type SpeiseScalarWhereWithAggregatesInput = {
  AND?: Prisma.SpeiseScalarWhereWithAggregatesInput | Prisma.SpeiseScalarWhereWithAggregatesInput[]
  OR?: Prisma.SpeiseScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SpeiseScalarWhereWithAggregatesInput | Prisma.SpeiseScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Speise"> | number
  speise?: Prisma.StringWithAggregatesFilter<"Speise"> | string
}

export type SpeiseCreateInput = {
  speise: string
  allergene?: Prisma.AllergenCreateNestedManyWithoutSpeisenInput
  bestellzeilen?: Prisma.BestellzeileCreateNestedManyWithoutSpeiseInput
}

export type SpeiseUncheckedCreateInput = {
  id?: number
  speise: string
  allergene?: Prisma.AllergenUncheckedCreateNestedManyWithoutSpeisenInput
  bestellzeilen?: Prisma.BestellzeileUncheckedCreateNestedManyWithoutSpeiseInput
}

export type SpeiseUpdateInput = {
  speise?: Prisma.StringFieldUpdateOperationsInput | string
  allergene?: Prisma.AllergenUpdateManyWithoutSpeisenNestedInput
  bestellzeilen?: Prisma.BestellzeileUpdateManyWithoutSpeiseNestedInput
}

export type SpeiseUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  speise?: Prisma.StringFieldUpdateOperationsInput | string
  allergene?: Prisma.AllergenUncheckedUpdateManyWithoutSpeisenNestedInput
  bestellzeilen?: Prisma.BestellzeileUncheckedUpdateManyWithoutSpeiseNestedInput
}

export type SpeiseCreateManyInput = {
  id?: number
  speise: string
}

export type SpeiseUpdateManyMutationInput = {
  speise?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SpeiseUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  speise?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SpeiseScalarRelationFilter = {
  is?: Prisma.SpeiseWhereInput
  isNot?: Prisma.SpeiseWhereInput
}

export type SpeiseCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  speise?: Prisma.SortOrder
}

export type SpeiseAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type SpeiseMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  speise?: Prisma.SortOrder
}

export type SpeiseMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  speise?: Prisma.SortOrder
}

export type SpeiseSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type SpeiseListRelationFilter = {
  every?: Prisma.SpeiseWhereInput
  some?: Prisma.SpeiseWhereInput
  none?: Prisma.SpeiseWhereInput
}

export type SpeiseOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SpeiseCreateNestedOneWithoutBestellzeilenInput = {
  create?: Prisma.XOR<Prisma.SpeiseCreateWithoutBestellzeilenInput, Prisma.SpeiseUncheckedCreateWithoutBestellzeilenInput>
  connectOrCreate?: Prisma.SpeiseCreateOrConnectWithoutBestellzeilenInput
  connect?: Prisma.SpeiseWhereUniqueInput
}

export type SpeiseUpdateOneRequiredWithoutBestellzeilenNestedInput = {
  create?: Prisma.XOR<Prisma.SpeiseCreateWithoutBestellzeilenInput, Prisma.SpeiseUncheckedCreateWithoutBestellzeilenInput>
  connectOrCreate?: Prisma.SpeiseCreateOrConnectWithoutBestellzeilenInput
  upsert?: Prisma.SpeiseUpsertWithoutBestellzeilenInput
  connect?: Prisma.SpeiseWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SpeiseUpdateToOneWithWhereWithoutBestellzeilenInput, Prisma.SpeiseUpdateWithoutBestellzeilenInput>, Prisma.SpeiseUncheckedUpdateWithoutBestellzeilenInput>
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type SpeiseCreateNestedManyWithoutAllergeneInput = {
  create?: Prisma.XOR<Prisma.SpeiseCreateWithoutAllergeneInput, Prisma.SpeiseUncheckedCreateWithoutAllergeneInput> | Prisma.SpeiseCreateWithoutAllergeneInput[] | Prisma.SpeiseUncheckedCreateWithoutAllergeneInput[]
  connectOrCreate?: Prisma.SpeiseCreateOrConnectWithoutAllergeneInput | Prisma.SpeiseCreateOrConnectWithoutAllergeneInput[]
  connect?: Prisma.SpeiseWhereUniqueInput | Prisma.SpeiseWhereUniqueInput[]
}

export type SpeiseUncheckedCreateNestedManyWithoutAllergeneInput = {
  create?: Prisma.XOR<Prisma.SpeiseCreateWithoutAllergeneInput, Prisma.SpeiseUncheckedCreateWithoutAllergeneInput> | Prisma.SpeiseCreateWithoutAllergeneInput[] | Prisma.SpeiseUncheckedCreateWithoutAllergeneInput[]
  connectOrCreate?: Prisma.SpeiseCreateOrConnectWithoutAllergeneInput | Prisma.SpeiseCreateOrConnectWithoutAllergeneInput[]
  connect?: Prisma.SpeiseWhereUniqueInput | Prisma.SpeiseWhereUniqueInput[]
}

export type SpeiseUpdateManyWithoutAllergeneNestedInput = {
  create?: Prisma.XOR<Prisma.SpeiseCreateWithoutAllergeneInput, Prisma.SpeiseUncheckedCreateWithoutAllergeneInput> | Prisma.SpeiseCreateWithoutAllergeneInput[] | Prisma.SpeiseUncheckedCreateWithoutAllergeneInput[]
  connectOrCreate?: Prisma.SpeiseCreateOrConnectWithoutAllergeneInput | Prisma.SpeiseCreateOrConnectWithoutAllergeneInput[]
  upsert?: Prisma.SpeiseUpsertWithWhereUniqueWithoutAllergeneInput | Prisma.SpeiseUpsertWithWhereUniqueWithoutAllergeneInput[]
  set?: Prisma.SpeiseWhereUniqueInput | Prisma.SpeiseWhereUniqueInput[]
  disconnect?: Prisma.SpeiseWhereUniqueInput | Prisma.SpeiseWhereUniqueInput[]
  delete?: Prisma.SpeiseWhereUniqueInput | Prisma.SpeiseWhereUniqueInput[]
  connect?: Prisma.SpeiseWhereUniqueInput | Prisma.SpeiseWhereUniqueInput[]
  update?: Prisma.SpeiseUpdateWithWhereUniqueWithoutAllergeneInput | Prisma.SpeiseUpdateWithWhereUniqueWithoutAllergeneInput[]
  updateMany?: Prisma.SpeiseUpdateManyWithWhereWithoutAllergeneInput | Prisma.SpeiseUpdateManyWithWhereWithoutAllergeneInput[]
  deleteMany?: Prisma.SpeiseScalarWhereInput | Prisma.SpeiseScalarWhereInput[]
}

export type SpeiseUncheckedUpdateManyWithoutAllergeneNestedInput = {
  create?: Prisma.XOR<Prisma.SpeiseCreateWithoutAllergeneInput, Prisma.SpeiseUncheckedCreateWithoutAllergeneInput> | Prisma.SpeiseCreateWithoutAllergeneInput[] | Prisma.SpeiseUncheckedCreateWithoutAllergeneInput[]
  connectOrCreate?: Prisma.SpeiseCreateOrConnectWithoutAllergeneInput | Prisma.SpeiseCreateOrConnectWithoutAllergeneInput[]
  upsert?: Prisma.SpeiseUpsertWithWhereUniqueWithoutAllergeneInput | Prisma.SpeiseUpsertWithWhereUniqueWithoutAllergeneInput[]
  set?: Prisma.SpeiseWhereUniqueInput | Prisma.SpeiseWhereUniqueInput[]
  disconnect?: Prisma.SpeiseWhereUniqueInput | Prisma.SpeiseWhereUniqueInput[]
  delete?: Prisma.SpeiseWhereUniqueInput | Prisma.SpeiseWhereUniqueInput[]
  connect?: Prisma.SpeiseWhereUniqueInput | Prisma.SpeiseWhereUniqueInput[]
  update?: Prisma.SpeiseUpdateWithWhereUniqueWithoutAllergeneInput | Prisma.SpeiseUpdateWithWhereUniqueWithoutAllergeneInput[]
  updateMany?: Prisma.SpeiseUpdateManyWithWhereWithoutAllergeneInput | Prisma.SpeiseUpdateManyWithWhereWithoutAllergeneInput[]
  deleteMany?: Prisma.SpeiseScalarWhereInput | Prisma.SpeiseScalarWhereInput[]
}

export type SpeiseCreateWithoutBestellzeilenInput = {
  speise: string
  allergene?: Prisma.AllergenCreateNestedManyWithoutSpeisenInput
}

export type SpeiseUncheckedCreateWithoutBestellzeilenInput = {
  id?: number
  speise: string
  allergene?: Prisma.AllergenUncheckedCreateNestedManyWithoutSpeisenInput
}

export type SpeiseCreateOrConnectWithoutBestellzeilenInput = {
  where: Prisma.SpeiseWhereUniqueInput
  create: Prisma.XOR<Prisma.SpeiseCreateWithoutBestellzeilenInput, Prisma.SpeiseUncheckedCreateWithoutBestellzeilenInput>
}

export type SpeiseUpsertWithoutBestellzeilenInput = {
  update: Prisma.XOR<Prisma.SpeiseUpdateWithoutBestellzeilenInput, Prisma.SpeiseUncheckedUpdateWithoutBestellzeilenInput>
  create: Prisma.XOR<Prisma.SpeiseCreateWithoutBestellzeilenInput, Prisma.SpeiseUncheckedCreateWithoutBestellzeilenInput>
  where?: Prisma.SpeiseWhereInput
}

export type SpeiseUpdateToOneWithWhereWithoutBestellzeilenInput = {
  where?: Prisma.SpeiseWhereInput
  data: Prisma.XOR<Prisma.SpeiseUpdateWithoutBestellzeilenInput, Prisma.SpeiseUncheckedUpdateWithoutBestellzeilenInput>
}

export type SpeiseUpdateWithoutBestellzeilenInput = {
  speise?: Prisma.StringFieldUpdateOperationsInput | string
  allergene?: Prisma.AllergenUpdateManyWithoutSpeisenNestedInput
}

export type SpeiseUncheckedUpdateWithoutBestellzeilenInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  speise?: Prisma.StringFieldUpdateOperationsInput | string
  allergene?: Prisma.AllergenUncheckedUpdateManyWithoutSpeisenNestedInput
}

export type SpeiseCreateWithoutAllergeneInput = {
  speise: string
  bestellzeilen?: Prisma.BestellzeileCreateNestedManyWithoutSpeiseInput
}

export type SpeiseUncheckedCreateWithoutAllergeneInput = {
  id?: number
  speise: string
  bestellzeilen?: Prisma.BestellzeileUncheckedCreateNestedManyWithoutSpeiseInput
}

export type SpeiseCreateOrConnectWithoutAllergeneInput = {
  where: Prisma.SpeiseWhereUniqueInput
  create: Prisma.XOR<Prisma.SpeiseCreateWithoutAllergeneInput, Prisma.SpeiseUncheckedCreateWithoutAllergeneInput>
}

export type SpeiseUpsertWithWhereUniqueWithoutAllergeneInput = {
  where: Prisma.SpeiseWhereUniqueInput
  update: Prisma.XOR<Prisma.SpeiseUpdateWithoutAllergeneInput, Prisma.SpeiseUncheckedUpdateWithoutAllergeneInput>
  create: Prisma.XOR<Prisma.SpeiseCreateWithoutAllergeneInput, Prisma.SpeiseUncheckedCreateWithoutAllergeneInput>
}

export type SpeiseUpdateWithWhereUniqueWithoutAllergeneInput = {
  where: Prisma.SpeiseWhereUniqueInput
  data: Prisma.XOR<Prisma.SpeiseUpdateWithoutAllergeneInput, Prisma.SpeiseUncheckedUpdateWithoutAllergeneInput>
}

export type SpeiseUpdateManyWithWhereWithoutAllergeneInput = {
  where: Prisma.SpeiseScalarWhereInput
  data: Prisma.XOR<Prisma.SpeiseUpdateManyMutationInput, Prisma.SpeiseUncheckedUpdateManyWithoutAllergeneInput>
}

export type SpeiseScalarWhereInput = {
  AND?: Prisma.SpeiseScalarWhereInput | Prisma.SpeiseScalarWhereInput[]
  OR?: Prisma.SpeiseScalarWhereInput[]
  NOT?: Prisma.SpeiseScalarWhereInput | Prisma.SpeiseScalarWhereInput[]
  id?: Prisma.IntFilter<"Speise"> | number
  speise?: Prisma.StringFilter<"Speise"> | string
}

export type SpeiseUpdateWithoutAllergeneInput = {
  speise?: Prisma.StringFieldUpdateOperationsInput | string
  bestellzeilen?: Prisma.BestellzeileUpdateManyWithoutSpeiseNestedInput
}

export type SpeiseUncheckedUpdateWithoutAllergeneInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  speise?: Prisma.StringFieldUpdateOperationsInput | string
  bestellzeilen?: Prisma.BestellzeileUncheckedUpdateManyWithoutSpeiseNestedInput
}

export type SpeiseUncheckedUpdateManyWithoutAllergeneInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  speise?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type SpeiseCountOutputType
 */

export type SpeiseCountOutputType = {
  allergene: number
  bestellzeilen: number
}

export type SpeiseCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  allergene?: boolean | SpeiseCountOutputTypeCountAllergeneArgs
  bestellzeilen?: boolean | SpeiseCountOutputTypeCountBestellzeilenArgs
}

/**
 * SpeiseCountOutputType without action
 */
export type SpeiseCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpeiseCountOutputType
   */
  select?: Prisma.SpeiseCountOutputTypeSelect<ExtArgs> | null
}

/**
 * SpeiseCountOutputType without action
 */
export type SpeiseCountOutputTypeCountAllergeneArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AllergenWhereInput
}

/**
 * SpeiseCountOutputType without action
 */
export type SpeiseCountOutputTypeCountBestellzeilenArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BestellzeileWhereInput
}


export type SpeiseSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  speise?: boolean
  allergene?: boolean | Prisma.Speise$allergeneArgs<ExtArgs>
  bestellzeilen?: boolean | Prisma.Speise$bestellzeilenArgs<ExtArgs>
  _count?: boolean | Prisma.SpeiseCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["speise"]>

export type SpeiseSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  speise?: boolean
}, ExtArgs["result"]["speise"]>

export type SpeiseSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  speise?: boolean
}, ExtArgs["result"]["speise"]>

export type SpeiseSelectScalar = {
  id?: boolean
  speise?: boolean
}

export type SpeiseOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "speise", ExtArgs["result"]["speise"]>
export type SpeiseInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  allergene?: boolean | Prisma.Speise$allergeneArgs<ExtArgs>
  bestellzeilen?: boolean | Prisma.Speise$bestellzeilenArgs<ExtArgs>
  _count?: boolean | Prisma.SpeiseCountOutputTypeDefaultArgs<ExtArgs>
}
export type SpeiseIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type SpeiseIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $SpeisePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Speise"
  objects: {
    allergene: Prisma.$AllergenPayload<ExtArgs>[]
    bestellzeilen: Prisma.$BestellzeilePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    speise: string
  }, ExtArgs["result"]["speise"]>
  composites: {}
}

export type SpeiseGetPayload<S extends boolean | null | undefined | SpeiseDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SpeisePayload, S>

export type SpeiseCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SpeiseFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SpeiseCountAggregateInputType | true
  }

export interface SpeiseDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Speise'], meta: { name: 'Speise' } }
  /**
   * Find zero or one Speise that matches the filter.
   * @param {SpeiseFindUniqueArgs} args - Arguments to find a Speise
   * @example
   * // Get one Speise
   * const speise = await prisma.speise.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SpeiseFindUniqueArgs>(args: Prisma.SelectSubset<T, SpeiseFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SpeiseClient<runtime.Types.Result.GetResult<Prisma.$SpeisePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Speise that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SpeiseFindUniqueOrThrowArgs} args - Arguments to find a Speise
   * @example
   * // Get one Speise
   * const speise = await prisma.speise.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SpeiseFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SpeiseFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SpeiseClient<runtime.Types.Result.GetResult<Prisma.$SpeisePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Speise that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpeiseFindFirstArgs} args - Arguments to find a Speise
   * @example
   * // Get one Speise
   * const speise = await prisma.speise.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SpeiseFindFirstArgs>(args?: Prisma.SelectSubset<T, SpeiseFindFirstArgs<ExtArgs>>): Prisma.Prisma__SpeiseClient<runtime.Types.Result.GetResult<Prisma.$SpeisePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Speise that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpeiseFindFirstOrThrowArgs} args - Arguments to find a Speise
   * @example
   * // Get one Speise
   * const speise = await prisma.speise.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SpeiseFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SpeiseFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SpeiseClient<runtime.Types.Result.GetResult<Prisma.$SpeisePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Speises that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpeiseFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Speises
   * const speises = await prisma.speise.findMany()
   * 
   * // Get first 10 Speises
   * const speises = await prisma.speise.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const speiseWithIdOnly = await prisma.speise.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SpeiseFindManyArgs>(args?: Prisma.SelectSubset<T, SpeiseFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SpeisePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Speise.
   * @param {SpeiseCreateArgs} args - Arguments to create a Speise.
   * @example
   * // Create one Speise
   * const Speise = await prisma.speise.create({
   *   data: {
   *     // ... data to create a Speise
   *   }
   * })
   * 
   */
  create<T extends SpeiseCreateArgs>(args: Prisma.SelectSubset<T, SpeiseCreateArgs<ExtArgs>>): Prisma.Prisma__SpeiseClient<runtime.Types.Result.GetResult<Prisma.$SpeisePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Speises.
   * @param {SpeiseCreateManyArgs} args - Arguments to create many Speises.
   * @example
   * // Create many Speises
   * const speise = await prisma.speise.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SpeiseCreateManyArgs>(args?: Prisma.SelectSubset<T, SpeiseCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Speises and returns the data saved in the database.
   * @param {SpeiseCreateManyAndReturnArgs} args - Arguments to create many Speises.
   * @example
   * // Create many Speises
   * const speise = await prisma.speise.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Speises and only return the `id`
   * const speiseWithIdOnly = await prisma.speise.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SpeiseCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SpeiseCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SpeisePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Speise.
   * @param {SpeiseDeleteArgs} args - Arguments to delete one Speise.
   * @example
   * // Delete one Speise
   * const Speise = await prisma.speise.delete({
   *   where: {
   *     // ... filter to delete one Speise
   *   }
   * })
   * 
   */
  delete<T extends SpeiseDeleteArgs>(args: Prisma.SelectSubset<T, SpeiseDeleteArgs<ExtArgs>>): Prisma.Prisma__SpeiseClient<runtime.Types.Result.GetResult<Prisma.$SpeisePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Speise.
   * @param {SpeiseUpdateArgs} args - Arguments to update one Speise.
   * @example
   * // Update one Speise
   * const speise = await prisma.speise.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SpeiseUpdateArgs>(args: Prisma.SelectSubset<T, SpeiseUpdateArgs<ExtArgs>>): Prisma.Prisma__SpeiseClient<runtime.Types.Result.GetResult<Prisma.$SpeisePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Speises.
   * @param {SpeiseDeleteManyArgs} args - Arguments to filter Speises to delete.
   * @example
   * // Delete a few Speises
   * const { count } = await prisma.speise.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SpeiseDeleteManyArgs>(args?: Prisma.SelectSubset<T, SpeiseDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Speises.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpeiseUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Speises
   * const speise = await prisma.speise.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SpeiseUpdateManyArgs>(args: Prisma.SelectSubset<T, SpeiseUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Speises and returns the data updated in the database.
   * @param {SpeiseUpdateManyAndReturnArgs} args - Arguments to update many Speises.
   * @example
   * // Update many Speises
   * const speise = await prisma.speise.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Speises and only return the `id`
   * const speiseWithIdOnly = await prisma.speise.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SpeiseUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SpeiseUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SpeisePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Speise.
   * @param {SpeiseUpsertArgs} args - Arguments to update or create a Speise.
   * @example
   * // Update or create a Speise
   * const speise = await prisma.speise.upsert({
   *   create: {
   *     // ... data to create a Speise
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Speise we want to update
   *   }
   * })
   */
  upsert<T extends SpeiseUpsertArgs>(args: Prisma.SelectSubset<T, SpeiseUpsertArgs<ExtArgs>>): Prisma.Prisma__SpeiseClient<runtime.Types.Result.GetResult<Prisma.$SpeisePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Speises.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpeiseCountArgs} args - Arguments to filter Speises to count.
   * @example
   * // Count the number of Speises
   * const count = await prisma.speise.count({
   *   where: {
   *     // ... the filter for the Speises we want to count
   *   }
   * })
  **/
  count<T extends SpeiseCountArgs>(
    args?: Prisma.Subset<T, SpeiseCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SpeiseCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Speise.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpeiseAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SpeiseAggregateArgs>(args: Prisma.Subset<T, SpeiseAggregateArgs>): Prisma.PrismaPromise<GetSpeiseAggregateType<T>>

  /**
   * Group by Speise.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpeiseGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SpeiseGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SpeiseGroupByArgs['orderBy'] }
      : { orderBy?: SpeiseGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SpeiseGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSpeiseGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Speise model
 */
readonly fields: SpeiseFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Speise.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SpeiseClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  allergene<T extends Prisma.Speise$allergeneArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Speise$allergeneArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AllergenPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  bestellzeilen<T extends Prisma.Speise$bestellzeilenArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Speise$bestellzeilenArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BestellzeilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Speise model
 */
export interface SpeiseFieldRefs {
  readonly id: Prisma.FieldRef<"Speise", 'Int'>
  readonly speise: Prisma.FieldRef<"Speise", 'String'>
}
    

// Custom InputTypes
/**
 * Speise findUnique
 */
export type SpeiseFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Speise
   */
  select?: Prisma.SpeiseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Speise
   */
  omit?: Prisma.SpeiseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpeiseInclude<ExtArgs> | null
  /**
   * Filter, which Speise to fetch.
   */
  where: Prisma.SpeiseWhereUniqueInput
}

/**
 * Speise findUniqueOrThrow
 */
export type SpeiseFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Speise
   */
  select?: Prisma.SpeiseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Speise
   */
  omit?: Prisma.SpeiseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpeiseInclude<ExtArgs> | null
  /**
   * Filter, which Speise to fetch.
   */
  where: Prisma.SpeiseWhereUniqueInput
}

/**
 * Speise findFirst
 */
export type SpeiseFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Speise
   */
  select?: Prisma.SpeiseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Speise
   */
  omit?: Prisma.SpeiseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpeiseInclude<ExtArgs> | null
  /**
   * Filter, which Speise to fetch.
   */
  where?: Prisma.SpeiseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Speises to fetch.
   */
  orderBy?: Prisma.SpeiseOrderByWithRelationInput | Prisma.SpeiseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Speises.
   */
  cursor?: Prisma.SpeiseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Speises from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Speises.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Speises.
   */
  distinct?: Prisma.SpeiseScalarFieldEnum | Prisma.SpeiseScalarFieldEnum[]
}

/**
 * Speise findFirstOrThrow
 */
export type SpeiseFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Speise
   */
  select?: Prisma.SpeiseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Speise
   */
  omit?: Prisma.SpeiseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpeiseInclude<ExtArgs> | null
  /**
   * Filter, which Speise to fetch.
   */
  where?: Prisma.SpeiseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Speises to fetch.
   */
  orderBy?: Prisma.SpeiseOrderByWithRelationInput | Prisma.SpeiseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Speises.
   */
  cursor?: Prisma.SpeiseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Speises from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Speises.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Speises.
   */
  distinct?: Prisma.SpeiseScalarFieldEnum | Prisma.SpeiseScalarFieldEnum[]
}

/**
 * Speise findMany
 */
export type SpeiseFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Speise
   */
  select?: Prisma.SpeiseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Speise
   */
  omit?: Prisma.SpeiseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpeiseInclude<ExtArgs> | null
  /**
   * Filter, which Speises to fetch.
   */
  where?: Prisma.SpeiseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Speises to fetch.
   */
  orderBy?: Prisma.SpeiseOrderByWithRelationInput | Prisma.SpeiseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Speises.
   */
  cursor?: Prisma.SpeiseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Speises from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Speises.
   */
  skip?: number
  distinct?: Prisma.SpeiseScalarFieldEnum | Prisma.SpeiseScalarFieldEnum[]
}

/**
 * Speise create
 */
export type SpeiseCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Speise
   */
  select?: Prisma.SpeiseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Speise
   */
  omit?: Prisma.SpeiseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpeiseInclude<ExtArgs> | null
  /**
   * The data needed to create a Speise.
   */
  data: Prisma.XOR<Prisma.SpeiseCreateInput, Prisma.SpeiseUncheckedCreateInput>
}

/**
 * Speise createMany
 */
export type SpeiseCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Speises.
   */
  data: Prisma.SpeiseCreateManyInput | Prisma.SpeiseCreateManyInput[]
}

/**
 * Speise createManyAndReturn
 */
export type SpeiseCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Speise
   */
  select?: Prisma.SpeiseSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Speise
   */
  omit?: Prisma.SpeiseOmit<ExtArgs> | null
  /**
   * The data used to create many Speises.
   */
  data: Prisma.SpeiseCreateManyInput | Prisma.SpeiseCreateManyInput[]
}

/**
 * Speise update
 */
export type SpeiseUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Speise
   */
  select?: Prisma.SpeiseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Speise
   */
  omit?: Prisma.SpeiseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpeiseInclude<ExtArgs> | null
  /**
   * The data needed to update a Speise.
   */
  data: Prisma.XOR<Prisma.SpeiseUpdateInput, Prisma.SpeiseUncheckedUpdateInput>
  /**
   * Choose, which Speise to update.
   */
  where: Prisma.SpeiseWhereUniqueInput
}

/**
 * Speise updateMany
 */
export type SpeiseUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Speises.
   */
  data: Prisma.XOR<Prisma.SpeiseUpdateManyMutationInput, Prisma.SpeiseUncheckedUpdateManyInput>
  /**
   * Filter which Speises to update
   */
  where?: Prisma.SpeiseWhereInput
  /**
   * Limit how many Speises to update.
   */
  limit?: number
}

/**
 * Speise updateManyAndReturn
 */
export type SpeiseUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Speise
   */
  select?: Prisma.SpeiseSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Speise
   */
  omit?: Prisma.SpeiseOmit<ExtArgs> | null
  /**
   * The data used to update Speises.
   */
  data: Prisma.XOR<Prisma.SpeiseUpdateManyMutationInput, Prisma.SpeiseUncheckedUpdateManyInput>
  /**
   * Filter which Speises to update
   */
  where?: Prisma.SpeiseWhereInput
  /**
   * Limit how many Speises to update.
   */
  limit?: number
}

/**
 * Speise upsert
 */
export type SpeiseUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Speise
   */
  select?: Prisma.SpeiseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Speise
   */
  omit?: Prisma.SpeiseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpeiseInclude<ExtArgs> | null
  /**
   * The filter to search for the Speise to update in case it exists.
   */
  where: Prisma.SpeiseWhereUniqueInput
  /**
   * In case the Speise found by the `where` argument doesn't exist, create a new Speise with this data.
   */
  create: Prisma.XOR<Prisma.SpeiseCreateInput, Prisma.SpeiseUncheckedCreateInput>
  /**
   * In case the Speise was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SpeiseUpdateInput, Prisma.SpeiseUncheckedUpdateInput>
}

/**
 * Speise delete
 */
export type SpeiseDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Speise
   */
  select?: Prisma.SpeiseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Speise
   */
  omit?: Prisma.SpeiseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpeiseInclude<ExtArgs> | null
  /**
   * Filter which Speise to delete.
   */
  where: Prisma.SpeiseWhereUniqueInput
}

/**
 * Speise deleteMany
 */
export type SpeiseDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Speises to delete
   */
  where?: Prisma.SpeiseWhereInput
  /**
   * Limit how many Speises to delete.
   */
  limit?: number
}

/**
 * Speise.allergene
 */
export type Speise$allergeneArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Allergen
   */
  select?: Prisma.AllergenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Allergen
   */
  omit?: Prisma.AllergenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AllergenInclude<ExtArgs> | null
  where?: Prisma.AllergenWhereInput
  orderBy?: Prisma.AllergenOrderByWithRelationInput | Prisma.AllergenOrderByWithRelationInput[]
  cursor?: Prisma.AllergenWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AllergenScalarFieldEnum | Prisma.AllergenScalarFieldEnum[]
}

/**
 * Speise.bestellzeilen
 */
export type Speise$bestellzeilenArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestellzeile
   */
  select?: Prisma.BestellzeileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestellzeile
   */
  omit?: Prisma.BestellzeileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestellzeileInclude<ExtArgs> | null
  where?: Prisma.BestellzeileWhereInput
  orderBy?: Prisma.BestellzeileOrderByWithRelationInput | Prisma.BestellzeileOrderByWithRelationInput[]
  cursor?: Prisma.BestellzeileWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BestellzeileScalarFieldEnum | Prisma.BestellzeileScalarFieldEnum[]
}

/**
 * Speise without action
 */
export type SpeiseDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Speise
   */
  select?: Prisma.SpeiseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Speise
   */
  omit?: Prisma.SpeiseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpeiseInclude<ExtArgs> | null
}
