
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Tisch` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Tisch
 * 
 */
export type TischModel = runtime.Types.Result.DefaultSelection<Prisma.$TischPayload>

export type AggregateTisch = {
  _count: TischCountAggregateOutputType | null
  _avg: TischAvgAggregateOutputType | null
  _sum: TischSumAggregateOutputType | null
  _min: TischMinAggregateOutputType | null
  _max: TischMaxAggregateOutputType | null
}

export type TischAvgAggregateOutputType = {
  id: number | null
}

export type TischSumAggregateOutputType = {
  id: number | null
}

export type TischMinAggregateOutputType = {
  id: number | null
}

export type TischMaxAggregateOutputType = {
  id: number | null
}

export type TischCountAggregateOutputType = {
  id: number
  _all: number
}


export type TischAvgAggregateInputType = {
  id?: true
}

export type TischSumAggregateInputType = {
  id?: true
}

export type TischMinAggregateInputType = {
  id?: true
}

export type TischMaxAggregateInputType = {
  id?: true
}

export type TischCountAggregateInputType = {
  id?: true
  _all?: true
}

export type TischAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Tisch to aggregate.
   */
  where?: Prisma.TischWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tisches to fetch.
   */
  orderBy?: Prisma.TischOrderByWithRelationInput | Prisma.TischOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TischWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tisches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tisches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Tisches
  **/
  _count?: true | TischCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TischAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TischSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TischMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TischMaxAggregateInputType
}

export type GetTischAggregateType<T extends TischAggregateArgs> = {
      [P in keyof T & keyof AggregateTisch]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTisch[P]>
    : Prisma.GetScalarType<T[P], AggregateTisch[P]>
}




export type TischGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TischWhereInput
  orderBy?: Prisma.TischOrderByWithAggregationInput | Prisma.TischOrderByWithAggregationInput[]
  by: Prisma.TischScalarFieldEnum[] | Prisma.TischScalarFieldEnum
  having?: Prisma.TischScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TischCountAggregateInputType | true
  _avg?: TischAvgAggregateInputType
  _sum?: TischSumAggregateInputType
  _min?: TischMinAggregateInputType
  _max?: TischMaxAggregateInputType
}

export type TischGroupByOutputType = {
  id: number
  _count: TischCountAggregateOutputType | null
  _avg: TischAvgAggregateOutputType | null
  _sum: TischSumAggregateOutputType | null
  _min: TischMinAggregateOutputType | null
  _max: TischMaxAggregateOutputType | null
}

type GetTischGroupByPayload<T extends TischGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TischGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TischGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TischGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TischGroupByOutputType[P]>
      }
    >
  >



export type TischWhereInput = {
  AND?: Prisma.TischWhereInput | Prisma.TischWhereInput[]
  OR?: Prisma.TischWhereInput[]
  NOT?: Prisma.TischWhereInput | Prisma.TischWhereInput[]
  id?: Prisma.IntFilter<"Tisch"> | number
  bestellung?: Prisma.XOR<Prisma.BestellungNullableScalarRelationFilter, Prisma.BestellungWhereInput> | null
}

export type TischOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  bestellung?: Prisma.BestellungOrderByWithRelationInput
}

export type TischWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.TischWhereInput | Prisma.TischWhereInput[]
  OR?: Prisma.TischWhereInput[]
  NOT?: Prisma.TischWhereInput | Prisma.TischWhereInput[]
  bestellung?: Prisma.XOR<Prisma.BestellungNullableScalarRelationFilter, Prisma.BestellungWhereInput> | null
}, "id">

export type TischOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  _count?: Prisma.TischCountOrderByAggregateInput
  _avg?: Prisma.TischAvgOrderByAggregateInput
  _max?: Prisma.TischMaxOrderByAggregateInput
  _min?: Prisma.TischMinOrderByAggregateInput
  _sum?: Prisma.TischSumOrderByAggregateInput
}

export type TischScalarWhereWithAggregatesInput = {
  AND?: Prisma.TischScalarWhereWithAggregatesInput | Prisma.TischScalarWhereWithAggregatesInput[]
  OR?: Prisma.TischScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TischScalarWhereWithAggregatesInput | Prisma.TischScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Tisch"> | number
}

export type TischCreateInput = {
  bestellung?: Prisma.BestellungCreateNestedOneWithoutTischInput
}

export type TischUncheckedCreateInput = {
  id?: number
  bestellung?: Prisma.BestellungUncheckedCreateNestedOneWithoutTischInput
}

export type TischUpdateInput = {
  bestellung?: Prisma.BestellungUpdateOneWithoutTischNestedInput
}

export type TischUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  bestellung?: Prisma.BestellungUncheckedUpdateOneWithoutTischNestedInput
}

export type TischCreateManyInput = {
  id?: number
}

export type TischUpdateManyMutationInput = {

}

export type TischUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TischCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type TischAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type TischMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type TischMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type TischSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type TischScalarRelationFilter = {
  is?: Prisma.TischWhereInput
  isNot?: Prisma.TischWhereInput
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type TischCreateNestedOneWithoutBestellungInput = {
  create?: Prisma.XOR<Prisma.TischCreateWithoutBestellungInput, Prisma.TischUncheckedCreateWithoutBestellungInput>
  connectOrCreate?: Prisma.TischCreateOrConnectWithoutBestellungInput
  connect?: Prisma.TischWhereUniqueInput
}

export type TischUpdateOneRequiredWithoutBestellungNestedInput = {
  create?: Prisma.XOR<Prisma.TischCreateWithoutBestellungInput, Prisma.TischUncheckedCreateWithoutBestellungInput>
  connectOrCreate?: Prisma.TischCreateOrConnectWithoutBestellungInput
  upsert?: Prisma.TischUpsertWithoutBestellungInput
  connect?: Prisma.TischWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TischUpdateToOneWithWhereWithoutBestellungInput, Prisma.TischUpdateWithoutBestellungInput>, Prisma.TischUncheckedUpdateWithoutBestellungInput>
}

export type TischCreateWithoutBestellungInput = {

}

export type TischUncheckedCreateWithoutBestellungInput = {
  id?: number
}

export type TischCreateOrConnectWithoutBestellungInput = {
  where: Prisma.TischWhereUniqueInput
  create: Prisma.XOR<Prisma.TischCreateWithoutBestellungInput, Prisma.TischUncheckedCreateWithoutBestellungInput>
}

export type TischUpsertWithoutBestellungInput = {
  update: Prisma.XOR<Prisma.TischUpdateWithoutBestellungInput, Prisma.TischUncheckedUpdateWithoutBestellungInput>
  create: Prisma.XOR<Prisma.TischCreateWithoutBestellungInput, Prisma.TischUncheckedCreateWithoutBestellungInput>
  where?: Prisma.TischWhereInput
}

export type TischUpdateToOneWithWhereWithoutBestellungInput = {
  where?: Prisma.TischWhereInput
  data: Prisma.XOR<Prisma.TischUpdateWithoutBestellungInput, Prisma.TischUncheckedUpdateWithoutBestellungInput>
}

export type TischUpdateWithoutBestellungInput = {

}

export type TischUncheckedUpdateWithoutBestellungInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
}



export type TischSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  bestellung?: boolean | Prisma.Tisch$bestellungArgs<ExtArgs>
}, ExtArgs["result"]["tisch"]>

export type TischSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
}, ExtArgs["result"]["tisch"]>

export type TischSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
}, ExtArgs["result"]["tisch"]>

export type TischSelectScalar = {
  id?: boolean
}

export type TischOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id", ExtArgs["result"]["tisch"]>
export type TischInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bestellung?: boolean | Prisma.Tisch$bestellungArgs<ExtArgs>
}
export type TischIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type TischIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $TischPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Tisch"
  objects: {
    bestellung: Prisma.$BestellungPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
  }, ExtArgs["result"]["tisch"]>
  composites: {}
}

export type TischGetPayload<S extends boolean | null | undefined | TischDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TischPayload, S>

export type TischCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TischFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TischCountAggregateInputType | true
  }

export interface TischDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Tisch'], meta: { name: 'Tisch' } }
  /**
   * Find zero or one Tisch that matches the filter.
   * @param {TischFindUniqueArgs} args - Arguments to find a Tisch
   * @example
   * // Get one Tisch
   * const tisch = await prisma.tisch.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TischFindUniqueArgs>(args: Prisma.SelectSubset<T, TischFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TischClient<runtime.Types.Result.GetResult<Prisma.$TischPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Tisch that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TischFindUniqueOrThrowArgs} args - Arguments to find a Tisch
   * @example
   * // Get one Tisch
   * const tisch = await prisma.tisch.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TischFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TischFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TischClient<runtime.Types.Result.GetResult<Prisma.$TischPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tisch that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TischFindFirstArgs} args - Arguments to find a Tisch
   * @example
   * // Get one Tisch
   * const tisch = await prisma.tisch.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TischFindFirstArgs>(args?: Prisma.SelectSubset<T, TischFindFirstArgs<ExtArgs>>): Prisma.Prisma__TischClient<runtime.Types.Result.GetResult<Prisma.$TischPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tisch that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TischFindFirstOrThrowArgs} args - Arguments to find a Tisch
   * @example
   * // Get one Tisch
   * const tisch = await prisma.tisch.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TischFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TischFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TischClient<runtime.Types.Result.GetResult<Prisma.$TischPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Tisches that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TischFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Tisches
   * const tisches = await prisma.tisch.findMany()
   * 
   * // Get first 10 Tisches
   * const tisches = await prisma.tisch.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tischWithIdOnly = await prisma.tisch.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TischFindManyArgs>(args?: Prisma.SelectSubset<T, TischFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TischPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Tisch.
   * @param {TischCreateArgs} args - Arguments to create a Tisch.
   * @example
   * // Create one Tisch
   * const Tisch = await prisma.tisch.create({
   *   data: {
   *     // ... data to create a Tisch
   *   }
   * })
   * 
   */
  create<T extends TischCreateArgs>(args: Prisma.SelectSubset<T, TischCreateArgs<ExtArgs>>): Prisma.Prisma__TischClient<runtime.Types.Result.GetResult<Prisma.$TischPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Tisches.
   * @param {TischCreateManyArgs} args - Arguments to create many Tisches.
   * @example
   * // Create many Tisches
   * const tisch = await prisma.tisch.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TischCreateManyArgs>(args?: Prisma.SelectSubset<T, TischCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Tisches and returns the data saved in the database.
   * @param {TischCreateManyAndReturnArgs} args - Arguments to create many Tisches.
   * @example
   * // Create many Tisches
   * const tisch = await prisma.tisch.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Tisches and only return the `id`
   * const tischWithIdOnly = await prisma.tisch.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TischCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TischCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TischPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Tisch.
   * @param {TischDeleteArgs} args - Arguments to delete one Tisch.
   * @example
   * // Delete one Tisch
   * const Tisch = await prisma.tisch.delete({
   *   where: {
   *     // ... filter to delete one Tisch
   *   }
   * })
   * 
   */
  delete<T extends TischDeleteArgs>(args: Prisma.SelectSubset<T, TischDeleteArgs<ExtArgs>>): Prisma.Prisma__TischClient<runtime.Types.Result.GetResult<Prisma.$TischPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Tisch.
   * @param {TischUpdateArgs} args - Arguments to update one Tisch.
   * @example
   * // Update one Tisch
   * const tisch = await prisma.tisch.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TischUpdateArgs>(args: Prisma.SelectSubset<T, TischUpdateArgs<ExtArgs>>): Prisma.Prisma__TischClient<runtime.Types.Result.GetResult<Prisma.$TischPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Tisches.
   * @param {TischDeleteManyArgs} args - Arguments to filter Tisches to delete.
   * @example
   * // Delete a few Tisches
   * const { count } = await prisma.tisch.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TischDeleteManyArgs>(args?: Prisma.SelectSubset<T, TischDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tisches.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TischUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Tisches
   * const tisch = await prisma.tisch.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TischUpdateManyArgs>(args: Prisma.SelectSubset<T, TischUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tisches and returns the data updated in the database.
   * @param {TischUpdateManyAndReturnArgs} args - Arguments to update many Tisches.
   * @example
   * // Update many Tisches
   * const tisch = await prisma.tisch.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Tisches and only return the `id`
   * const tischWithIdOnly = await prisma.tisch.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TischUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TischUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TischPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Tisch.
   * @param {TischUpsertArgs} args - Arguments to update or create a Tisch.
   * @example
   * // Update or create a Tisch
   * const tisch = await prisma.tisch.upsert({
   *   create: {
   *     // ... data to create a Tisch
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Tisch we want to update
   *   }
   * })
   */
  upsert<T extends TischUpsertArgs>(args: Prisma.SelectSubset<T, TischUpsertArgs<ExtArgs>>): Prisma.Prisma__TischClient<runtime.Types.Result.GetResult<Prisma.$TischPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Tisches.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TischCountArgs} args - Arguments to filter Tisches to count.
   * @example
   * // Count the number of Tisches
   * const count = await prisma.tisch.count({
   *   where: {
   *     // ... the filter for the Tisches we want to count
   *   }
   * })
  **/
  count<T extends TischCountArgs>(
    args?: Prisma.Subset<T, TischCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TischCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Tisch.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TischAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TischAggregateArgs>(args: Prisma.Subset<T, TischAggregateArgs>): Prisma.PrismaPromise<GetTischAggregateType<T>>

  /**
   * Group by Tisch.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TischGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TischGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TischGroupByArgs['orderBy'] }
      : { orderBy?: TischGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TischGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTischGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Tisch model
 */
readonly fields: TischFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Tisch.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TischClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  bestellung<T extends Prisma.Tisch$bestellungArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Tisch$bestellungArgs<ExtArgs>>): Prisma.Prisma__BestellungClient<runtime.Types.Result.GetResult<Prisma.$BestellungPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Tisch model
 */
export interface TischFieldRefs {
  readonly id: Prisma.FieldRef<"Tisch", 'Int'>
}
    

// Custom InputTypes
/**
 * Tisch findUnique
 */
export type TischFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tisch
   */
  select?: Prisma.TischSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tisch
   */
  omit?: Prisma.TischOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TischInclude<ExtArgs> | null
  /**
   * Filter, which Tisch to fetch.
   */
  where: Prisma.TischWhereUniqueInput
}

/**
 * Tisch findUniqueOrThrow
 */
export type TischFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tisch
   */
  select?: Prisma.TischSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tisch
   */
  omit?: Prisma.TischOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TischInclude<ExtArgs> | null
  /**
   * Filter, which Tisch to fetch.
   */
  where: Prisma.TischWhereUniqueInput
}

/**
 * Tisch findFirst
 */
export type TischFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tisch
   */
  select?: Prisma.TischSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tisch
   */
  omit?: Prisma.TischOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TischInclude<ExtArgs> | null
  /**
   * Filter, which Tisch to fetch.
   */
  where?: Prisma.TischWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tisches to fetch.
   */
  orderBy?: Prisma.TischOrderByWithRelationInput | Prisma.TischOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tisches.
   */
  cursor?: Prisma.TischWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tisches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tisches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tisches.
   */
  distinct?: Prisma.TischScalarFieldEnum | Prisma.TischScalarFieldEnum[]
}

/**
 * Tisch findFirstOrThrow
 */
export type TischFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tisch
   */
  select?: Prisma.TischSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tisch
   */
  omit?: Prisma.TischOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TischInclude<ExtArgs> | null
  /**
   * Filter, which Tisch to fetch.
   */
  where?: Prisma.TischWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tisches to fetch.
   */
  orderBy?: Prisma.TischOrderByWithRelationInput | Prisma.TischOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tisches.
   */
  cursor?: Prisma.TischWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tisches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tisches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tisches.
   */
  distinct?: Prisma.TischScalarFieldEnum | Prisma.TischScalarFieldEnum[]
}

/**
 * Tisch findMany
 */
export type TischFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tisch
   */
  select?: Prisma.TischSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tisch
   */
  omit?: Prisma.TischOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TischInclude<ExtArgs> | null
  /**
   * Filter, which Tisches to fetch.
   */
  where?: Prisma.TischWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tisches to fetch.
   */
  orderBy?: Prisma.TischOrderByWithRelationInput | Prisma.TischOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Tisches.
   */
  cursor?: Prisma.TischWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tisches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tisches.
   */
  skip?: number
  distinct?: Prisma.TischScalarFieldEnum | Prisma.TischScalarFieldEnum[]
}

/**
 * Tisch create
 */
export type TischCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tisch
   */
  select?: Prisma.TischSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tisch
   */
  omit?: Prisma.TischOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TischInclude<ExtArgs> | null
  /**
   * The data needed to create a Tisch.
   */
  data?: Prisma.XOR<Prisma.TischCreateInput, Prisma.TischUncheckedCreateInput>
}

/**
 * Tisch createMany
 */
export type TischCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Tisches.
   */
  data: Prisma.TischCreateManyInput | Prisma.TischCreateManyInput[]
}

/**
 * Tisch createManyAndReturn
 */
export type TischCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tisch
   */
  select?: Prisma.TischSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Tisch
   */
  omit?: Prisma.TischOmit<ExtArgs> | null
  /**
   * The data used to create many Tisches.
   */
  data: Prisma.TischCreateManyInput | Prisma.TischCreateManyInput[]
}

/**
 * Tisch update
 */
export type TischUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tisch
   */
  select?: Prisma.TischSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tisch
   */
  omit?: Prisma.TischOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TischInclude<ExtArgs> | null
  /**
   * The data needed to update a Tisch.
   */
  data: Prisma.XOR<Prisma.TischUpdateInput, Prisma.TischUncheckedUpdateInput>
  /**
   * Choose, which Tisch to update.
   */
  where: Prisma.TischWhereUniqueInput
}

/**
 * Tisch updateMany
 */
export type TischUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Tisches.
   */
  data: Prisma.XOR<Prisma.TischUpdateManyMutationInput, Prisma.TischUncheckedUpdateManyInput>
  /**
   * Filter which Tisches to update
   */
  where?: Prisma.TischWhereInput
  /**
   * Limit how many Tisches to update.
   */
  limit?: number
}

/**
 * Tisch updateManyAndReturn
 */
export type TischUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tisch
   */
  select?: Prisma.TischSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Tisch
   */
  omit?: Prisma.TischOmit<ExtArgs> | null
  /**
   * The data used to update Tisches.
   */
  data: Prisma.XOR<Prisma.TischUpdateManyMutationInput, Prisma.TischUncheckedUpdateManyInput>
  /**
   * Filter which Tisches to update
   */
  where?: Prisma.TischWhereInput
  /**
   * Limit how many Tisches to update.
   */
  limit?: number
}

/**
 * Tisch upsert
 */
export type TischUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tisch
   */
  select?: Prisma.TischSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tisch
   */
  omit?: Prisma.TischOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TischInclude<ExtArgs> | null
  /**
   * The filter to search for the Tisch to update in case it exists.
   */
  where: Prisma.TischWhereUniqueInput
  /**
   * In case the Tisch found by the `where` argument doesn't exist, create a new Tisch with this data.
   */
  create: Prisma.XOR<Prisma.TischCreateInput, Prisma.TischUncheckedCreateInput>
  /**
   * In case the Tisch was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TischUpdateInput, Prisma.TischUncheckedUpdateInput>
}

/**
 * Tisch delete
 */
export type TischDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tisch
   */
  select?: Prisma.TischSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tisch
   */
  omit?: Prisma.TischOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TischInclude<ExtArgs> | null
  /**
   * Filter which Tisch to delete.
   */
  where: Prisma.TischWhereUniqueInput
}

/**
 * Tisch deleteMany
 */
export type TischDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Tisches to delete
   */
  where?: Prisma.TischWhereInput
  /**
   * Limit how many Tisches to delete.
   */
  limit?: number
}

/**
 * Tisch.bestellung
 */
export type Tisch$bestellungArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestellung
   */
  select?: Prisma.BestellungSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestellung
   */
  omit?: Prisma.BestellungOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestellungInclude<ExtArgs> | null
  where?: Prisma.BestellungWhereInput
}

/**
 * Tisch without action
 */
export type TischDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tisch
   */
  select?: Prisma.TischSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tisch
   */
  omit?: Prisma.TischOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TischInclude<ExtArgs> | null
}
