
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Bestellzeile` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Bestellzeile
 * 
 */
export type BestellzeileModel = runtime.Types.Result.DefaultSelection<Prisma.$BestellzeilePayload>

export type AggregateBestellzeile = {
  _count: BestellzeileCountAggregateOutputType | null
  _avg: BestellzeileAvgAggregateOutputType | null
  _sum: BestellzeileSumAggregateOutputType | null
  _min: BestellzeileMinAggregateOutputType | null
  _max: BestellzeileMaxAggregateOutputType | null
}

export type BestellzeileAvgAggregateOutputType = {
  id: number | null
  bestellungId: number | null
  speiseId: number | null
  menge: number | null
}

export type BestellzeileSumAggregateOutputType = {
  id: number | null
  bestellungId: number | null
  speiseId: number | null
  menge: number | null
}

export type BestellzeileMinAggregateOutputType = {
  id: number | null
  bestellungId: number | null
  speiseId: number | null
  menge: number | null
}

export type BestellzeileMaxAggregateOutputType = {
  id: number | null
  bestellungId: number | null
  speiseId: number | null
  menge: number | null
}

export type BestellzeileCountAggregateOutputType = {
  id: number
  bestellungId: number
  speiseId: number
  menge: number
  _all: number
}


export type BestellzeileAvgAggregateInputType = {
  id?: true
  bestellungId?: true
  speiseId?: true
  menge?: true
}

export type BestellzeileSumAggregateInputType = {
  id?: true
  bestellungId?: true
  speiseId?: true
  menge?: true
}

export type BestellzeileMinAggregateInputType = {
  id?: true
  bestellungId?: true
  speiseId?: true
  menge?: true
}

export type BestellzeileMaxAggregateInputType = {
  id?: true
  bestellungId?: true
  speiseId?: true
  menge?: true
}

export type BestellzeileCountAggregateInputType = {
  id?: true
  bestellungId?: true
  speiseId?: true
  menge?: true
  _all?: true
}

export type BestellzeileAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Bestellzeile to aggregate.
   */
  where?: Prisma.BestellzeileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Bestellzeiles to fetch.
   */
  orderBy?: Prisma.BestellzeileOrderByWithRelationInput | Prisma.BestellzeileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BestellzeileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Bestellzeiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Bestellzeiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Bestellzeiles
  **/
  _count?: true | BestellzeileCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: BestellzeileAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: BestellzeileSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BestellzeileMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BestellzeileMaxAggregateInputType
}

export type GetBestellzeileAggregateType<T extends BestellzeileAggregateArgs> = {
      [P in keyof T & keyof AggregateBestellzeile]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBestellzeile[P]>
    : Prisma.GetScalarType<T[P], AggregateBestellzeile[P]>
}




export type BestellzeileGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BestellzeileWhereInput
  orderBy?: Prisma.BestellzeileOrderByWithAggregationInput | Prisma.BestellzeileOrderByWithAggregationInput[]
  by: Prisma.BestellzeileScalarFieldEnum[] | Prisma.BestellzeileScalarFieldEnum
  having?: Prisma.BestellzeileScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BestellzeileCountAggregateInputType | true
  _avg?: BestellzeileAvgAggregateInputType
  _sum?: BestellzeileSumAggregateInputType
  _min?: BestellzeileMinAggregateInputType
  _max?: BestellzeileMaxAggregateInputType
}

export type BestellzeileGroupByOutputType = {
  id: number
  bestellungId: number
  speiseId: number
  menge: number
  _count: BestellzeileCountAggregateOutputType | null
  _avg: BestellzeileAvgAggregateOutputType | null
  _sum: BestellzeileSumAggregateOutputType | null
  _min: BestellzeileMinAggregateOutputType | null
  _max: BestellzeileMaxAggregateOutputType | null
}

type GetBestellzeileGroupByPayload<T extends BestellzeileGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BestellzeileGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BestellzeileGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BestellzeileGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BestellzeileGroupByOutputType[P]>
      }
    >
  >



export type BestellzeileWhereInput = {
  AND?: Prisma.BestellzeileWhereInput | Prisma.BestellzeileWhereInput[]
  OR?: Prisma.BestellzeileWhereInput[]
  NOT?: Prisma.BestellzeileWhereInput | Prisma.BestellzeileWhereInput[]
  id?: Prisma.IntFilter<"Bestellzeile"> | number
  bestellungId?: Prisma.IntFilter<"Bestellzeile"> | number
  speiseId?: Prisma.IntFilter<"Bestellzeile"> | number
  menge?: Prisma.IntFilter<"Bestellzeile"> | number
  bestellung?: Prisma.XOR<Prisma.BestellungScalarRelationFilter, Prisma.BestellungWhereInput>
  speise?: Prisma.XOR<Prisma.SpeiseScalarRelationFilter, Prisma.SpeiseWhereInput>
}

export type BestellzeileOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  bestellungId?: Prisma.SortOrder
  speiseId?: Prisma.SortOrder
  menge?: Prisma.SortOrder
  bestellung?: Prisma.BestellungOrderByWithRelationInput
  speise?: Prisma.SpeiseOrderByWithRelationInput
}

export type BestellzeileWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.BestellzeileWhereInput | Prisma.BestellzeileWhereInput[]
  OR?: Prisma.BestellzeileWhereInput[]
  NOT?: Prisma.BestellzeileWhereInput | Prisma.BestellzeileWhereInput[]
  bestellungId?: Prisma.IntFilter<"Bestellzeile"> | number
  speiseId?: Prisma.IntFilter<"Bestellzeile"> | number
  menge?: Prisma.IntFilter<"Bestellzeile"> | number
  bestellung?: Prisma.XOR<Prisma.BestellungScalarRelationFilter, Prisma.BestellungWhereInput>
  speise?: Prisma.XOR<Prisma.SpeiseScalarRelationFilter, Prisma.SpeiseWhereInput>
}, "id">

export type BestellzeileOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  bestellungId?: Prisma.SortOrder
  speiseId?: Prisma.SortOrder
  menge?: Prisma.SortOrder
  _count?: Prisma.BestellzeileCountOrderByAggregateInput
  _avg?: Prisma.BestellzeileAvgOrderByAggregateInput
  _max?: Prisma.BestellzeileMaxOrderByAggregateInput
  _min?: Prisma.BestellzeileMinOrderByAggregateInput
  _sum?: Prisma.BestellzeileSumOrderByAggregateInput
}

export type BestellzeileScalarWhereWithAggregatesInput = {
  AND?: Prisma.BestellzeileScalarWhereWithAggregatesInput | Prisma.BestellzeileScalarWhereWithAggregatesInput[]
  OR?: Prisma.BestellzeileScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BestellzeileScalarWhereWithAggregatesInput | Prisma.BestellzeileScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Bestellzeile"> | number
  bestellungId?: Prisma.IntWithAggregatesFilter<"Bestellzeile"> | number
  speiseId?: Prisma.IntWithAggregatesFilter<"Bestellzeile"> | number
  menge?: Prisma.IntWithAggregatesFilter<"Bestellzeile"> | number
}

export type BestellzeileCreateInput = {
  menge: number
  bestellung: Prisma.BestellungCreateNestedOneWithoutBestellzeilenInput
  speise: Prisma.SpeiseCreateNestedOneWithoutBestellzeilenInput
}

export type BestellzeileUncheckedCreateInput = {
  id?: number
  bestellungId: number
  speiseId: number
  menge: number
}

export type BestellzeileUpdateInput = {
  menge?: Prisma.IntFieldUpdateOperationsInput | number
  bestellung?: Prisma.BestellungUpdateOneRequiredWithoutBestellzeilenNestedInput
  speise?: Prisma.SpeiseUpdateOneRequiredWithoutBestellzeilenNestedInput
}

export type BestellzeileUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  bestellungId?: Prisma.IntFieldUpdateOperationsInput | number
  speiseId?: Prisma.IntFieldUpdateOperationsInput | number
  menge?: Prisma.IntFieldUpdateOperationsInput | number
}

export type BestellzeileCreateManyInput = {
  id?: number
  bestellungId: number
  speiseId: number
  menge: number
}

export type BestellzeileUpdateManyMutationInput = {
  menge?: Prisma.IntFieldUpdateOperationsInput | number
}

export type BestellzeileUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  bestellungId?: Prisma.IntFieldUpdateOperationsInput | number
  speiseId?: Prisma.IntFieldUpdateOperationsInput | number
  menge?: Prisma.IntFieldUpdateOperationsInput | number
}

export type BestellzeileListRelationFilter = {
  every?: Prisma.BestellzeileWhereInput
  some?: Prisma.BestellzeileWhereInput
  none?: Prisma.BestellzeileWhereInput
}

export type BestellzeileOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BestellzeileCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  bestellungId?: Prisma.SortOrder
  speiseId?: Prisma.SortOrder
  menge?: Prisma.SortOrder
}

export type BestellzeileAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  bestellungId?: Prisma.SortOrder
  speiseId?: Prisma.SortOrder
  menge?: Prisma.SortOrder
}

export type BestellzeileMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  bestellungId?: Prisma.SortOrder
  speiseId?: Prisma.SortOrder
  menge?: Prisma.SortOrder
}

export type BestellzeileMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  bestellungId?: Prisma.SortOrder
  speiseId?: Prisma.SortOrder
  menge?: Prisma.SortOrder
}

export type BestellzeileSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  bestellungId?: Prisma.SortOrder
  speiseId?: Prisma.SortOrder
  menge?: Prisma.SortOrder
}

export type BestellzeileCreateNestedManyWithoutSpeiseInput = {
  create?: Prisma.XOR<Prisma.BestellzeileCreateWithoutSpeiseInput, Prisma.BestellzeileUncheckedCreateWithoutSpeiseInput> | Prisma.BestellzeileCreateWithoutSpeiseInput[] | Prisma.BestellzeileUncheckedCreateWithoutSpeiseInput[]
  connectOrCreate?: Prisma.BestellzeileCreateOrConnectWithoutSpeiseInput | Prisma.BestellzeileCreateOrConnectWithoutSpeiseInput[]
  createMany?: Prisma.BestellzeileCreateManySpeiseInputEnvelope
  connect?: Prisma.BestellzeileWhereUniqueInput | Prisma.BestellzeileWhereUniqueInput[]
}

export type BestellzeileUncheckedCreateNestedManyWithoutSpeiseInput = {
  create?: Prisma.XOR<Prisma.BestellzeileCreateWithoutSpeiseInput, Prisma.BestellzeileUncheckedCreateWithoutSpeiseInput> | Prisma.BestellzeileCreateWithoutSpeiseInput[] | Prisma.BestellzeileUncheckedCreateWithoutSpeiseInput[]
  connectOrCreate?: Prisma.BestellzeileCreateOrConnectWithoutSpeiseInput | Prisma.BestellzeileCreateOrConnectWithoutSpeiseInput[]
  createMany?: Prisma.BestellzeileCreateManySpeiseInputEnvelope
  connect?: Prisma.BestellzeileWhereUniqueInput | Prisma.BestellzeileWhereUniqueInput[]
}

export type BestellzeileUpdateManyWithoutSpeiseNestedInput = {
  create?: Prisma.XOR<Prisma.BestellzeileCreateWithoutSpeiseInput, Prisma.BestellzeileUncheckedCreateWithoutSpeiseInput> | Prisma.BestellzeileCreateWithoutSpeiseInput[] | Prisma.BestellzeileUncheckedCreateWithoutSpeiseInput[]
  connectOrCreate?: Prisma.BestellzeileCreateOrConnectWithoutSpeiseInput | Prisma.BestellzeileCreateOrConnectWithoutSpeiseInput[]
  upsert?: Prisma.BestellzeileUpsertWithWhereUniqueWithoutSpeiseInput | Prisma.BestellzeileUpsertWithWhereUniqueWithoutSpeiseInput[]
  createMany?: Prisma.BestellzeileCreateManySpeiseInputEnvelope
  set?: Prisma.BestellzeileWhereUniqueInput | Prisma.BestellzeileWhereUniqueInput[]
  disconnect?: Prisma.BestellzeileWhereUniqueInput | Prisma.BestellzeileWhereUniqueInput[]
  delete?: Prisma.BestellzeileWhereUniqueInput | Prisma.BestellzeileWhereUniqueInput[]
  connect?: Prisma.BestellzeileWhereUniqueInput | Prisma.BestellzeileWhereUniqueInput[]
  update?: Prisma.BestellzeileUpdateWithWhereUniqueWithoutSpeiseInput | Prisma.BestellzeileUpdateWithWhereUniqueWithoutSpeiseInput[]
  updateMany?: Prisma.BestellzeileUpdateManyWithWhereWithoutSpeiseInput | Prisma.BestellzeileUpdateManyWithWhereWithoutSpeiseInput[]
  deleteMany?: Prisma.BestellzeileScalarWhereInput | Prisma.BestellzeileScalarWhereInput[]
}

export type BestellzeileUncheckedUpdateManyWithoutSpeiseNestedInput = {
  create?: Prisma.XOR<Prisma.BestellzeileCreateWithoutSpeiseInput, Prisma.BestellzeileUncheckedCreateWithoutSpeiseInput> | Prisma.BestellzeileCreateWithoutSpeiseInput[] | Prisma.BestellzeileUncheckedCreateWithoutSpeiseInput[]
  connectOrCreate?: Prisma.BestellzeileCreateOrConnectWithoutSpeiseInput | Prisma.BestellzeileCreateOrConnectWithoutSpeiseInput[]
  upsert?: Prisma.BestellzeileUpsertWithWhereUniqueWithoutSpeiseInput | Prisma.BestellzeileUpsertWithWhereUniqueWithoutSpeiseInput[]
  createMany?: Prisma.BestellzeileCreateManySpeiseInputEnvelope
  set?: Prisma.BestellzeileWhereUniqueInput | Prisma.BestellzeileWhereUniqueInput[]
  disconnect?: Prisma.BestellzeileWhereUniqueInput | Prisma.BestellzeileWhereUniqueInput[]
  delete?: Prisma.BestellzeileWhereUniqueInput | Prisma.BestellzeileWhereUniqueInput[]
  connect?: Prisma.BestellzeileWhereUniqueInput | Prisma.BestellzeileWhereUniqueInput[]
  update?: Prisma.BestellzeileUpdateWithWhereUniqueWithoutSpeiseInput | Prisma.BestellzeileUpdateWithWhereUniqueWithoutSpeiseInput[]
  updateMany?: Prisma.BestellzeileUpdateManyWithWhereWithoutSpeiseInput | Prisma.BestellzeileUpdateManyWithWhereWithoutSpeiseInput[]
  deleteMany?: Prisma.BestellzeileScalarWhereInput | Prisma.BestellzeileScalarWhereInput[]
}

export type BestellzeileCreateNestedManyWithoutBestellungInput = {
  create?: Prisma.XOR<Prisma.BestellzeileCreateWithoutBestellungInput, Prisma.BestellzeileUncheckedCreateWithoutBestellungInput> | Prisma.BestellzeileCreateWithoutBestellungInput[] | Prisma.BestellzeileUncheckedCreateWithoutBestellungInput[]
  connectOrCreate?: Prisma.BestellzeileCreateOrConnectWithoutBestellungInput | Prisma.BestellzeileCreateOrConnectWithoutBestellungInput[]
  createMany?: Prisma.BestellzeileCreateManyBestellungInputEnvelope
  connect?: Prisma.BestellzeileWhereUniqueInput | Prisma.BestellzeileWhereUniqueInput[]
}

export type BestellzeileUncheckedCreateNestedManyWithoutBestellungInput = {
  create?: Prisma.XOR<Prisma.BestellzeileCreateWithoutBestellungInput, Prisma.BestellzeileUncheckedCreateWithoutBestellungInput> | Prisma.BestellzeileCreateWithoutBestellungInput[] | Prisma.BestellzeileUncheckedCreateWithoutBestellungInput[]
  connectOrCreate?: Prisma.BestellzeileCreateOrConnectWithoutBestellungInput | Prisma.BestellzeileCreateOrConnectWithoutBestellungInput[]
  createMany?: Prisma.BestellzeileCreateManyBestellungInputEnvelope
  connect?: Prisma.BestellzeileWhereUniqueInput | Prisma.BestellzeileWhereUniqueInput[]
}

export type BestellzeileUpdateManyWithoutBestellungNestedInput = {
  create?: Prisma.XOR<Prisma.BestellzeileCreateWithoutBestellungInput, Prisma.BestellzeileUncheckedCreateWithoutBestellungInput> | Prisma.BestellzeileCreateWithoutBestellungInput[] | Prisma.BestellzeileUncheckedCreateWithoutBestellungInput[]
  connectOrCreate?: Prisma.BestellzeileCreateOrConnectWithoutBestellungInput | Prisma.BestellzeileCreateOrConnectWithoutBestellungInput[]
  upsert?: Prisma.BestellzeileUpsertWithWhereUniqueWithoutBestellungInput | Prisma.BestellzeileUpsertWithWhereUniqueWithoutBestellungInput[]
  createMany?: Prisma.BestellzeileCreateManyBestellungInputEnvelope
  set?: Prisma.BestellzeileWhereUniqueInput | Prisma.BestellzeileWhereUniqueInput[]
  disconnect?: Prisma.BestellzeileWhereUniqueInput | Prisma.BestellzeileWhereUniqueInput[]
  delete?: Prisma.BestellzeileWhereUniqueInput | Prisma.BestellzeileWhereUniqueInput[]
  connect?: Prisma.BestellzeileWhereUniqueInput | Prisma.BestellzeileWhereUniqueInput[]
  update?: Prisma.BestellzeileUpdateWithWhereUniqueWithoutBestellungInput | Prisma.BestellzeileUpdateWithWhereUniqueWithoutBestellungInput[]
  updateMany?: Prisma.BestellzeileUpdateManyWithWhereWithoutBestellungInput | Prisma.BestellzeileUpdateManyWithWhereWithoutBestellungInput[]
  deleteMany?: Prisma.BestellzeileScalarWhereInput | Prisma.BestellzeileScalarWhereInput[]
}

export type BestellzeileUncheckedUpdateManyWithoutBestellungNestedInput = {
  create?: Prisma.XOR<Prisma.BestellzeileCreateWithoutBestellungInput, Prisma.BestellzeileUncheckedCreateWithoutBestellungInput> | Prisma.BestellzeileCreateWithoutBestellungInput[] | Prisma.BestellzeileUncheckedCreateWithoutBestellungInput[]
  connectOrCreate?: Prisma.BestellzeileCreateOrConnectWithoutBestellungInput | Prisma.BestellzeileCreateOrConnectWithoutBestellungInput[]
  upsert?: Prisma.BestellzeileUpsertWithWhereUniqueWithoutBestellungInput | Prisma.BestellzeileUpsertWithWhereUniqueWithoutBestellungInput[]
  createMany?: Prisma.BestellzeileCreateManyBestellungInputEnvelope
  set?: Prisma.BestellzeileWhereUniqueInput | Prisma.BestellzeileWhereUniqueInput[]
  disconnect?: Prisma.BestellzeileWhereUniqueInput | Prisma.BestellzeileWhereUniqueInput[]
  delete?: Prisma.BestellzeileWhereUniqueInput | Prisma.BestellzeileWhereUniqueInput[]
  connect?: Prisma.BestellzeileWhereUniqueInput | Prisma.BestellzeileWhereUniqueInput[]
  update?: Prisma.BestellzeileUpdateWithWhereUniqueWithoutBestellungInput | Prisma.BestellzeileUpdateWithWhereUniqueWithoutBestellungInput[]
  updateMany?: Prisma.BestellzeileUpdateManyWithWhereWithoutBestellungInput | Prisma.BestellzeileUpdateManyWithWhereWithoutBestellungInput[]
  deleteMany?: Prisma.BestellzeileScalarWhereInput | Prisma.BestellzeileScalarWhereInput[]
}

export type BestellzeileCreateWithoutSpeiseInput = {
  menge: number
  bestellung: Prisma.BestellungCreateNestedOneWithoutBestellzeilenInput
}

export type BestellzeileUncheckedCreateWithoutSpeiseInput = {
  id?: number
  bestellungId: number
  menge: number
}

export type BestellzeileCreateOrConnectWithoutSpeiseInput = {
  where: Prisma.BestellzeileWhereUniqueInput
  create: Prisma.XOR<Prisma.BestellzeileCreateWithoutSpeiseInput, Prisma.BestellzeileUncheckedCreateWithoutSpeiseInput>
}

export type BestellzeileCreateManySpeiseInputEnvelope = {
  data: Prisma.BestellzeileCreateManySpeiseInput | Prisma.BestellzeileCreateManySpeiseInput[]
}

export type BestellzeileUpsertWithWhereUniqueWithoutSpeiseInput = {
  where: Prisma.BestellzeileWhereUniqueInput
  update: Prisma.XOR<Prisma.BestellzeileUpdateWithoutSpeiseInput, Prisma.BestellzeileUncheckedUpdateWithoutSpeiseInput>
  create: Prisma.XOR<Prisma.BestellzeileCreateWithoutSpeiseInput, Prisma.BestellzeileUncheckedCreateWithoutSpeiseInput>
}

export type BestellzeileUpdateWithWhereUniqueWithoutSpeiseInput = {
  where: Prisma.BestellzeileWhereUniqueInput
  data: Prisma.XOR<Prisma.BestellzeileUpdateWithoutSpeiseInput, Prisma.BestellzeileUncheckedUpdateWithoutSpeiseInput>
}

export type BestellzeileUpdateManyWithWhereWithoutSpeiseInput = {
  where: Prisma.BestellzeileScalarWhereInput
  data: Prisma.XOR<Prisma.BestellzeileUpdateManyMutationInput, Prisma.BestellzeileUncheckedUpdateManyWithoutSpeiseInput>
}

export type BestellzeileScalarWhereInput = {
  AND?: Prisma.BestellzeileScalarWhereInput | Prisma.BestellzeileScalarWhereInput[]
  OR?: Prisma.BestellzeileScalarWhereInput[]
  NOT?: Prisma.BestellzeileScalarWhereInput | Prisma.BestellzeileScalarWhereInput[]
  id?: Prisma.IntFilter<"Bestellzeile"> | number
  bestellungId?: Prisma.IntFilter<"Bestellzeile"> | number
  speiseId?: Prisma.IntFilter<"Bestellzeile"> | number
  menge?: Prisma.IntFilter<"Bestellzeile"> | number
}

export type BestellzeileCreateWithoutBestellungInput = {
  menge: number
  speise: Prisma.SpeiseCreateNestedOneWithoutBestellzeilenInput
}

export type BestellzeileUncheckedCreateWithoutBestellungInput = {
  id?: number
  speiseId: number
  menge: number
}

export type BestellzeileCreateOrConnectWithoutBestellungInput = {
  where: Prisma.BestellzeileWhereUniqueInput
  create: Prisma.XOR<Prisma.BestellzeileCreateWithoutBestellungInput, Prisma.BestellzeileUncheckedCreateWithoutBestellungInput>
}

export type BestellzeileCreateManyBestellungInputEnvelope = {
  data: Prisma.BestellzeileCreateManyBestellungInput | Prisma.BestellzeileCreateManyBestellungInput[]
}

export type BestellzeileUpsertWithWhereUniqueWithoutBestellungInput = {
  where: Prisma.BestellzeileWhereUniqueInput
  update: Prisma.XOR<Prisma.BestellzeileUpdateWithoutBestellungInput, Prisma.BestellzeileUncheckedUpdateWithoutBestellungInput>
  create: Prisma.XOR<Prisma.BestellzeileCreateWithoutBestellungInput, Prisma.BestellzeileUncheckedCreateWithoutBestellungInput>
}

export type BestellzeileUpdateWithWhereUniqueWithoutBestellungInput = {
  where: Prisma.BestellzeileWhereUniqueInput
  data: Prisma.XOR<Prisma.BestellzeileUpdateWithoutBestellungInput, Prisma.BestellzeileUncheckedUpdateWithoutBestellungInput>
}

export type BestellzeileUpdateManyWithWhereWithoutBestellungInput = {
  where: Prisma.BestellzeileScalarWhereInput
  data: Prisma.XOR<Prisma.BestellzeileUpdateManyMutationInput, Prisma.BestellzeileUncheckedUpdateManyWithoutBestellungInput>
}

export type BestellzeileCreateManySpeiseInput = {
  id?: number
  bestellungId: number
  menge: number
}

export type BestellzeileUpdateWithoutSpeiseInput = {
  menge?: Prisma.IntFieldUpdateOperationsInput | number
  bestellung?: Prisma.BestellungUpdateOneRequiredWithoutBestellzeilenNestedInput
}

export type BestellzeileUncheckedUpdateWithoutSpeiseInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  bestellungId?: Prisma.IntFieldUpdateOperationsInput | number
  menge?: Prisma.IntFieldUpdateOperationsInput | number
}

export type BestellzeileUncheckedUpdateManyWithoutSpeiseInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  bestellungId?: Prisma.IntFieldUpdateOperationsInput | number
  menge?: Prisma.IntFieldUpdateOperationsInput | number
}

export type BestellzeileCreateManyBestellungInput = {
  id?: number
  speiseId: number
  menge: number
}

export type BestellzeileUpdateWithoutBestellungInput = {
  menge?: Prisma.IntFieldUpdateOperationsInput | number
  speise?: Prisma.SpeiseUpdateOneRequiredWithoutBestellzeilenNestedInput
}

export type BestellzeileUncheckedUpdateWithoutBestellungInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  speiseId?: Prisma.IntFieldUpdateOperationsInput | number
  menge?: Prisma.IntFieldUpdateOperationsInput | number
}

export type BestellzeileUncheckedUpdateManyWithoutBestellungInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  speiseId?: Prisma.IntFieldUpdateOperationsInput | number
  menge?: Prisma.IntFieldUpdateOperationsInput | number
}



export type BestellzeileSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  bestellungId?: boolean
  speiseId?: boolean
  menge?: boolean
  bestellung?: boolean | Prisma.BestellungDefaultArgs<ExtArgs>
  speise?: boolean | Prisma.SpeiseDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bestellzeile"]>

export type BestellzeileSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  bestellungId?: boolean
  speiseId?: boolean
  menge?: boolean
  bestellung?: boolean | Prisma.BestellungDefaultArgs<ExtArgs>
  speise?: boolean | Prisma.SpeiseDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bestellzeile"]>

export type BestellzeileSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  bestellungId?: boolean
  speiseId?: boolean
  menge?: boolean
  bestellung?: boolean | Prisma.BestellungDefaultArgs<ExtArgs>
  speise?: boolean | Prisma.SpeiseDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bestellzeile"]>

export type BestellzeileSelectScalar = {
  id?: boolean
  bestellungId?: boolean
  speiseId?: boolean
  menge?: boolean
}

export type BestellzeileOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "bestellungId" | "speiseId" | "menge", ExtArgs["result"]["bestellzeile"]>
export type BestellzeileInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bestellung?: boolean | Prisma.BestellungDefaultArgs<ExtArgs>
  speise?: boolean | Prisma.SpeiseDefaultArgs<ExtArgs>
}
export type BestellzeileIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bestellung?: boolean | Prisma.BestellungDefaultArgs<ExtArgs>
  speise?: boolean | Prisma.SpeiseDefaultArgs<ExtArgs>
}
export type BestellzeileIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bestellung?: boolean | Prisma.BestellungDefaultArgs<ExtArgs>
  speise?: boolean | Prisma.SpeiseDefaultArgs<ExtArgs>
}

export type $BestellzeilePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Bestellzeile"
  objects: {
    bestellung: Prisma.$BestellungPayload<ExtArgs>
    speise: Prisma.$SpeisePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    bestellungId: number
    speiseId: number
    menge: number
  }, ExtArgs["result"]["bestellzeile"]>
  composites: {}
}

export type BestellzeileGetPayload<S extends boolean | null | undefined | BestellzeileDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BestellzeilePayload, S>

export type BestellzeileCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BestellzeileFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BestellzeileCountAggregateInputType | true
  }

export interface BestellzeileDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Bestellzeile'], meta: { name: 'Bestellzeile' } }
  /**
   * Find zero or one Bestellzeile that matches the filter.
   * @param {BestellzeileFindUniqueArgs} args - Arguments to find a Bestellzeile
   * @example
   * // Get one Bestellzeile
   * const bestellzeile = await prisma.bestellzeile.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BestellzeileFindUniqueArgs>(args: Prisma.SelectSubset<T, BestellzeileFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BestellzeileClient<runtime.Types.Result.GetResult<Prisma.$BestellzeilePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Bestellzeile that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BestellzeileFindUniqueOrThrowArgs} args - Arguments to find a Bestellzeile
   * @example
   * // Get one Bestellzeile
   * const bestellzeile = await prisma.bestellzeile.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BestellzeileFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BestellzeileFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BestellzeileClient<runtime.Types.Result.GetResult<Prisma.$BestellzeilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Bestellzeile that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestellzeileFindFirstArgs} args - Arguments to find a Bestellzeile
   * @example
   * // Get one Bestellzeile
   * const bestellzeile = await prisma.bestellzeile.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BestellzeileFindFirstArgs>(args?: Prisma.SelectSubset<T, BestellzeileFindFirstArgs<ExtArgs>>): Prisma.Prisma__BestellzeileClient<runtime.Types.Result.GetResult<Prisma.$BestellzeilePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Bestellzeile that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestellzeileFindFirstOrThrowArgs} args - Arguments to find a Bestellzeile
   * @example
   * // Get one Bestellzeile
   * const bestellzeile = await prisma.bestellzeile.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BestellzeileFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BestellzeileFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BestellzeileClient<runtime.Types.Result.GetResult<Prisma.$BestellzeilePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Bestellzeiles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestellzeileFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Bestellzeiles
   * const bestellzeiles = await prisma.bestellzeile.findMany()
   * 
   * // Get first 10 Bestellzeiles
   * const bestellzeiles = await prisma.bestellzeile.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const bestellzeileWithIdOnly = await prisma.bestellzeile.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BestellzeileFindManyArgs>(args?: Prisma.SelectSubset<T, BestellzeileFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BestellzeilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Bestellzeile.
   * @param {BestellzeileCreateArgs} args - Arguments to create a Bestellzeile.
   * @example
   * // Create one Bestellzeile
   * const Bestellzeile = await prisma.bestellzeile.create({
   *   data: {
   *     // ... data to create a Bestellzeile
   *   }
   * })
   * 
   */
  create<T extends BestellzeileCreateArgs>(args: Prisma.SelectSubset<T, BestellzeileCreateArgs<ExtArgs>>): Prisma.Prisma__BestellzeileClient<runtime.Types.Result.GetResult<Prisma.$BestellzeilePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Bestellzeiles.
   * @param {BestellzeileCreateManyArgs} args - Arguments to create many Bestellzeiles.
   * @example
   * // Create many Bestellzeiles
   * const bestellzeile = await prisma.bestellzeile.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BestellzeileCreateManyArgs>(args?: Prisma.SelectSubset<T, BestellzeileCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Bestellzeiles and returns the data saved in the database.
   * @param {BestellzeileCreateManyAndReturnArgs} args - Arguments to create many Bestellzeiles.
   * @example
   * // Create many Bestellzeiles
   * const bestellzeile = await prisma.bestellzeile.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Bestellzeiles and only return the `id`
   * const bestellzeileWithIdOnly = await prisma.bestellzeile.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BestellzeileCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BestellzeileCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BestellzeilePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Bestellzeile.
   * @param {BestellzeileDeleteArgs} args - Arguments to delete one Bestellzeile.
   * @example
   * // Delete one Bestellzeile
   * const Bestellzeile = await prisma.bestellzeile.delete({
   *   where: {
   *     // ... filter to delete one Bestellzeile
   *   }
   * })
   * 
   */
  delete<T extends BestellzeileDeleteArgs>(args: Prisma.SelectSubset<T, BestellzeileDeleteArgs<ExtArgs>>): Prisma.Prisma__BestellzeileClient<runtime.Types.Result.GetResult<Prisma.$BestellzeilePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Bestellzeile.
   * @param {BestellzeileUpdateArgs} args - Arguments to update one Bestellzeile.
   * @example
   * // Update one Bestellzeile
   * const bestellzeile = await prisma.bestellzeile.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BestellzeileUpdateArgs>(args: Prisma.SelectSubset<T, BestellzeileUpdateArgs<ExtArgs>>): Prisma.Prisma__BestellzeileClient<runtime.Types.Result.GetResult<Prisma.$BestellzeilePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Bestellzeiles.
   * @param {BestellzeileDeleteManyArgs} args - Arguments to filter Bestellzeiles to delete.
   * @example
   * // Delete a few Bestellzeiles
   * const { count } = await prisma.bestellzeile.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BestellzeileDeleteManyArgs>(args?: Prisma.SelectSubset<T, BestellzeileDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Bestellzeiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestellzeileUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Bestellzeiles
   * const bestellzeile = await prisma.bestellzeile.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BestellzeileUpdateManyArgs>(args: Prisma.SelectSubset<T, BestellzeileUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Bestellzeiles and returns the data updated in the database.
   * @param {BestellzeileUpdateManyAndReturnArgs} args - Arguments to update many Bestellzeiles.
   * @example
   * // Update many Bestellzeiles
   * const bestellzeile = await prisma.bestellzeile.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Bestellzeiles and only return the `id`
   * const bestellzeileWithIdOnly = await prisma.bestellzeile.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BestellzeileUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BestellzeileUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BestellzeilePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Bestellzeile.
   * @param {BestellzeileUpsertArgs} args - Arguments to update or create a Bestellzeile.
   * @example
   * // Update or create a Bestellzeile
   * const bestellzeile = await prisma.bestellzeile.upsert({
   *   create: {
   *     // ... data to create a Bestellzeile
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Bestellzeile we want to update
   *   }
   * })
   */
  upsert<T extends BestellzeileUpsertArgs>(args: Prisma.SelectSubset<T, BestellzeileUpsertArgs<ExtArgs>>): Prisma.Prisma__BestellzeileClient<runtime.Types.Result.GetResult<Prisma.$BestellzeilePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Bestellzeiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestellzeileCountArgs} args - Arguments to filter Bestellzeiles to count.
   * @example
   * // Count the number of Bestellzeiles
   * const count = await prisma.bestellzeile.count({
   *   where: {
   *     // ... the filter for the Bestellzeiles we want to count
   *   }
   * })
  **/
  count<T extends BestellzeileCountArgs>(
    args?: Prisma.Subset<T, BestellzeileCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BestellzeileCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Bestellzeile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestellzeileAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BestellzeileAggregateArgs>(args: Prisma.Subset<T, BestellzeileAggregateArgs>): Prisma.PrismaPromise<GetBestellzeileAggregateType<T>>

  /**
   * Group by Bestellzeile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestellzeileGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BestellzeileGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BestellzeileGroupByArgs['orderBy'] }
      : { orderBy?: BestellzeileGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BestellzeileGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBestellzeileGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Bestellzeile model
 */
readonly fields: BestellzeileFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Bestellzeile.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BestellzeileClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  bestellung<T extends Prisma.BestellungDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BestellungDefaultArgs<ExtArgs>>): Prisma.Prisma__BestellungClient<runtime.Types.Result.GetResult<Prisma.$BestellungPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  speise<T extends Prisma.SpeiseDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SpeiseDefaultArgs<ExtArgs>>): Prisma.Prisma__SpeiseClient<runtime.Types.Result.GetResult<Prisma.$SpeisePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Bestellzeile model
 */
export interface BestellzeileFieldRefs {
  readonly id: Prisma.FieldRef<"Bestellzeile", 'Int'>
  readonly bestellungId: Prisma.FieldRef<"Bestellzeile", 'Int'>
  readonly speiseId: Prisma.FieldRef<"Bestellzeile", 'Int'>
  readonly menge: Prisma.FieldRef<"Bestellzeile", 'Int'>
}
    

// Custom InputTypes
/**
 * Bestellzeile findUnique
 */
export type BestellzeileFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestellzeile
   */
  select?: Prisma.BestellzeileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestellzeile
   */
  omit?: Prisma.BestellzeileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestellzeileInclude<ExtArgs> | null
  /**
   * Filter, which Bestellzeile to fetch.
   */
  where: Prisma.BestellzeileWhereUniqueInput
}

/**
 * Bestellzeile findUniqueOrThrow
 */
export type BestellzeileFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestellzeile
   */
  select?: Prisma.BestellzeileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestellzeile
   */
  omit?: Prisma.BestellzeileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestellzeileInclude<ExtArgs> | null
  /**
   * Filter, which Bestellzeile to fetch.
   */
  where: Prisma.BestellzeileWhereUniqueInput
}

/**
 * Bestellzeile findFirst
 */
export type BestellzeileFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestellzeile
   */
  select?: Prisma.BestellzeileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestellzeile
   */
  omit?: Prisma.BestellzeileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestellzeileInclude<ExtArgs> | null
  /**
   * Filter, which Bestellzeile to fetch.
   */
  where?: Prisma.BestellzeileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Bestellzeiles to fetch.
   */
  orderBy?: Prisma.BestellzeileOrderByWithRelationInput | Prisma.BestellzeileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Bestellzeiles.
   */
  cursor?: Prisma.BestellzeileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Bestellzeiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Bestellzeiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Bestellzeiles.
   */
  distinct?: Prisma.BestellzeileScalarFieldEnum | Prisma.BestellzeileScalarFieldEnum[]
}

/**
 * Bestellzeile findFirstOrThrow
 */
export type BestellzeileFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestellzeile
   */
  select?: Prisma.BestellzeileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestellzeile
   */
  omit?: Prisma.BestellzeileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestellzeileInclude<ExtArgs> | null
  /**
   * Filter, which Bestellzeile to fetch.
   */
  where?: Prisma.BestellzeileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Bestellzeiles to fetch.
   */
  orderBy?: Prisma.BestellzeileOrderByWithRelationInput | Prisma.BestellzeileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Bestellzeiles.
   */
  cursor?: Prisma.BestellzeileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Bestellzeiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Bestellzeiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Bestellzeiles.
   */
  distinct?: Prisma.BestellzeileScalarFieldEnum | Prisma.BestellzeileScalarFieldEnum[]
}

/**
 * Bestellzeile findMany
 */
export type BestellzeileFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestellzeile
   */
  select?: Prisma.BestellzeileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestellzeile
   */
  omit?: Prisma.BestellzeileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestellzeileInclude<ExtArgs> | null
  /**
   * Filter, which Bestellzeiles to fetch.
   */
  where?: Prisma.BestellzeileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Bestellzeiles to fetch.
   */
  orderBy?: Prisma.BestellzeileOrderByWithRelationInput | Prisma.BestellzeileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Bestellzeiles.
   */
  cursor?: Prisma.BestellzeileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Bestellzeiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Bestellzeiles.
   */
  skip?: number
  distinct?: Prisma.BestellzeileScalarFieldEnum | Prisma.BestellzeileScalarFieldEnum[]
}

/**
 * Bestellzeile create
 */
export type BestellzeileCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestellzeile
   */
  select?: Prisma.BestellzeileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestellzeile
   */
  omit?: Prisma.BestellzeileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestellzeileInclude<ExtArgs> | null
  /**
   * The data needed to create a Bestellzeile.
   */
  data: Prisma.XOR<Prisma.BestellzeileCreateInput, Prisma.BestellzeileUncheckedCreateInput>
}

/**
 * Bestellzeile createMany
 */
export type BestellzeileCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Bestellzeiles.
   */
  data: Prisma.BestellzeileCreateManyInput | Prisma.BestellzeileCreateManyInput[]
}

/**
 * Bestellzeile createManyAndReturn
 */
export type BestellzeileCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestellzeile
   */
  select?: Prisma.BestellzeileSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Bestellzeile
   */
  omit?: Prisma.BestellzeileOmit<ExtArgs> | null
  /**
   * The data used to create many Bestellzeiles.
   */
  data: Prisma.BestellzeileCreateManyInput | Prisma.BestellzeileCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestellzeileIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Bestellzeile update
 */
export type BestellzeileUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestellzeile
   */
  select?: Prisma.BestellzeileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestellzeile
   */
  omit?: Prisma.BestellzeileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestellzeileInclude<ExtArgs> | null
  /**
   * The data needed to update a Bestellzeile.
   */
  data: Prisma.XOR<Prisma.BestellzeileUpdateInput, Prisma.BestellzeileUncheckedUpdateInput>
  /**
   * Choose, which Bestellzeile to update.
   */
  where: Prisma.BestellzeileWhereUniqueInput
}

/**
 * Bestellzeile updateMany
 */
export type BestellzeileUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Bestellzeiles.
   */
  data: Prisma.XOR<Prisma.BestellzeileUpdateManyMutationInput, Prisma.BestellzeileUncheckedUpdateManyInput>
  /**
   * Filter which Bestellzeiles to update
   */
  where?: Prisma.BestellzeileWhereInput
  /**
   * Limit how many Bestellzeiles to update.
   */
  limit?: number
}

/**
 * Bestellzeile updateManyAndReturn
 */
export type BestellzeileUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestellzeile
   */
  select?: Prisma.BestellzeileSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Bestellzeile
   */
  omit?: Prisma.BestellzeileOmit<ExtArgs> | null
  /**
   * The data used to update Bestellzeiles.
   */
  data: Prisma.XOR<Prisma.BestellzeileUpdateManyMutationInput, Prisma.BestellzeileUncheckedUpdateManyInput>
  /**
   * Filter which Bestellzeiles to update
   */
  where?: Prisma.BestellzeileWhereInput
  /**
   * Limit how many Bestellzeiles to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestellzeileIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Bestellzeile upsert
 */
export type BestellzeileUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestellzeile
   */
  select?: Prisma.BestellzeileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestellzeile
   */
  omit?: Prisma.BestellzeileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestellzeileInclude<ExtArgs> | null
  /**
   * The filter to search for the Bestellzeile to update in case it exists.
   */
  where: Prisma.BestellzeileWhereUniqueInput
  /**
   * In case the Bestellzeile found by the `where` argument doesn't exist, create a new Bestellzeile with this data.
   */
  create: Prisma.XOR<Prisma.BestellzeileCreateInput, Prisma.BestellzeileUncheckedCreateInput>
  /**
   * In case the Bestellzeile was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BestellzeileUpdateInput, Prisma.BestellzeileUncheckedUpdateInput>
}

/**
 * Bestellzeile delete
 */
export type BestellzeileDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestellzeile
   */
  select?: Prisma.BestellzeileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestellzeile
   */
  omit?: Prisma.BestellzeileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestellzeileInclude<ExtArgs> | null
  /**
   * Filter which Bestellzeile to delete.
   */
  where: Prisma.BestellzeileWhereUniqueInput
}

/**
 * Bestellzeile deleteMany
 */
export type BestellzeileDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Bestellzeiles to delete
   */
  where?: Prisma.BestellzeileWhereInput
  /**
   * Limit how many Bestellzeiles to delete.
   */
  limit?: number
}

/**
 * Bestellzeile without action
 */
export type BestellzeileDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestellzeile
   */
  select?: Prisma.BestellzeileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestellzeile
   */
  omit?: Prisma.BestellzeileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestellzeileInclude<ExtArgs> | null
}
