// // This file was generated by Prisma and assumes you have installed the following:
// // npm install --save-dev prisma dotenv
// import "@std/dotenv";
// import { defineConfig, env } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: env("DATABASE_URL"),
//   },
// });

// @ts-types="npm:@types/node"
/// <reference types="deno.ns" />
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: Deno.env.get("DATABASE_URL") || "file:./database.db",
  },
});
