
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.ts'
export { Prisma }
export * as $Enums from './enums.ts'
export * from './enums.ts';
/**
 * Model Tisch
 * 
 */
export type Tisch = Prisma.TischModel
/**
 * Model Speise
 * 
 */
export type Speise = Prisma.SpeiseModel
/**
 * Model Allergen
 * 
 */
export type Allergen = Prisma.AllergenModel
/**
 * Model Bestellung
 * 
 */
export type Bestellung = Prisma.BestellungModel
/**
 * Model Bestellzeile
 * 
 */
export type Bestellzeile = Prisma.BestellzeileModel
